/**
 * COMPLETE Sanatana Dharma Knowledge Graph
 * 
 * This is the definitive knowledge structure containing:
 * - All major Shruti (Vedas, Upanishads)
 * - All major Smriti (Epics, Shastras)
 * - All major Puranas
 * - All 6 Darshanas + Vedanta schools
 * - Yoga systems, Tantric traditions, Bhakti schools
 * - Core concepts and practices
 * - Historical and intellectual lineage
 */

import type { KnowledgeNode, KnowledgeEdge } from "@/types/knowledge";

/**
 * SEMANTIC ZONES - Organize knowledge into meaningful clusters
 */
export const semanticZones = {
  SHRUTI: { label: "Shruti", color: "#B8860B", order: 0, x: 5, y: 20 },
  SMRITI: { label: "Smriti", color: "#DAA520", order: 1, x: 25, y: 20 },
  PURANAS: { label: "Puranas", color: "#CD853F", order: 2, x: 45, y: 20 },
  DARSHANAS: { label: "Darshanas", color: "#7C3AED", order: 3, x: 65, y: 20 },
  YOGA_SYSTEMS: { label: "Yoga Systems", color: "#0891B2", order: 4, x: 85, y: 20 },
  TANTRA: { label: "Tantra", color: "#EC4899", order: 5, x: 5, y: 60 },
  BHAKTI: { label: "Bhakti Traditions", color: "#DC2626", order: 6, x: 25, y: 60 },
  CONCEPTS: { label: "Core Concepts", color: "#16A34A", order: 7, x: 45, y: 60 },
  PRACTICES: { label: "Practices", color: "#CA8A04", order: 8, x: 65, y: 60 },
  ACHARYAS: { label: "Saints & Acharyas", color: "#8B5CF6", order: 9, x: 85, y: 60 },
} as const;

/**
 * ============================================================
 * COMPREHENSIVE KNOWLEDGE NODES
 * ============================================================
 */

export const comprehensiveKnowledgeNodes: KnowledgeNode[] = [
  // ROOT NODE
  {
    id: "sanatana-dharma-root",
    slug: "sanatana-dharma",
    title: "Sanatana Dharma",
    subtitle: "The Eternal Way",
    summary: "The complete knowledge system of Indian philosophy, scriptures, practices, and spiritual traditions.",
    nodeType: "TRADITION",
    zone: "ROOT",
    depth: 0,
    x: 50,
    y: 50,
    tags: ["root", "overview"],
  },

  // ============================================================
  // SHRUTI - REVEALED KNOWLEDGE
  // ============================================================

  {
    id: "shruti",
    slug: "shruti",
    title: "Shruti",
    subtitle: "Revealed Knowledge",
    summary: "The foundational revealed scriptures including the four Vedas, Brahmanas, Aranyakas, and Upanishads.",
    nodeType: "TRADITION",
    zone: "SHRUTI",
    parentId: "sanatana-dharma-root",
    depth: 1,
    x: 5,
    y: 30,
    tags: ["foundation", "eternal"],
  },

  // Vedas - Four Primary Texts
  {
    id: "vedas",
    slug: "vedas",
    title: "The Four Vedas",
    summary: "The foundational corpus of Sanskrit spiritual knowledge.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "shruti",
    depth: 2,
    x: 2,
    y: 25,
  },

  {
    id: "rigveda",
    slug: "rigveda",
    title: "Rigveda",
    summary: "Collection of Vedic Sanskrit hymns. The oldest of the Vedas.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "vedas",
    depth: 3,
    x: 0.5,
    y: 20,
    tags: ["ancient"],
    href: "/scriptures/rigveda",
  },

  {
    id: "yajurveda",
    slug: "yajurveda",
    title: "Yajurveda",
    summary: "The Veda of sacrificial formulas and ritual action.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "vedas",
    depth: 3,
    x: 1.5,
    y: 20,
    tags: ["ritual"],
    href: "/scriptures/yajurveda",
  },

  {
    id: "samaveda",
    slug: "samaveda",
    title: "Samaveda",
    summary: "The Veda of chant and musical recitation. Foundation of Indian classical music.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "vedas",
    depth: 3,
    x: 2.5,
    y: 20,
    tags: ["music"],
    href: "/scriptures/samaveda",
  },

  {
    id: "atharvaveda",
    slug: "atharvaveda",
    title: "Atharvaveda",
    summary: "The Veda of practical wisdom, including healing, ethics, and daily concerns.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "vedas",
    depth: 3,
    x: 3.5,
    y: 20,
    tags: ["practical"],
    href: "/scriptures/atharvaveda",
  },

  // Vedanga (Auxiliary texts for understanding Vedas)
  {
    id: "vedanga",
    slug: "vedanga",
    title: "Vedanga",
    subtitle: "Limbs of the Vedas",
    summary: "Six auxiliary disciplines for proper understanding and recitation of the Vedas.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "shruti",
    depth: 2,
    x: 3.5,
    y: 28,
  },

  {
    id: "shiksha",
    slug: "shiksha",
    title: "Shiksha",
    summary: "Phonetics and pronunciation of Vedic texts.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "vedanga",
    depth: 3,
    x: 3,
    y: 24,
  },

  {
    id: "kalpa",
    slug: "kalpa",
    title: "Kalpa",
    summary: "Ritual procedures and their correct performance.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "vedanga",
    depth: 3,
    x: 3.5,
    y: 24,
  },

  {
    id: "vyakarana",
    slug: "vyakarana",
    title: "Vyakarana",
    summary: "Sanskrit grammar and linguistic science.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "vedanga",
    depth: 3,
    x: 4,
    y: 24,
  },

  {
    id: "nirukta",
    slug: "nirukta",
    title: "Nirukta",
    summary: "Etymology and meaning of Vedic words.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "vedanga",
    depth: 3,
    x: 4.5,
    y: 24,
  },

  {
    id: "chandas",
    slug: "chandas",
    title: "Chandas",
    summary: "Vedic meter and prosody.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "vedanga",
    depth: 3,
    x: 5,
    y: 24,
  },

  {
    id: "jyotisha",
    slug: "jyotisha",
    title: "Jyotisha",
    summary: "Astronomy and auspicious timing for rituals.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "vedanga",
    depth: 3,
    x: 5.5,
    y: 24,
  },

  // Brahmanas and Aranyakas
  {
    id: "brahmanas",
    slug: "brahmanas",
    title: "Brahmanas",
    summary: "Prose commentaries on the Vedas explaining rituals and their spiritual significance.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "shruti",
    depth: 2,
    x: 6.5,
    y: 28,
  },

  {
    id: "aranyakas",
    slug: "aranyakas",
    title: "Aranyakas",
    summary: "Forest texts transitioning from ritual to philosophical inquiry.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "shruti",
    depth: 2,
    x: 8,
    y: 28,
  },

  // Upanishads - Principal
  {
    id: "principal-upanishads",
    slug: "principal-upanishads",
    title: "Principal Upanishads",
    subtitle: "The 10 Major Upanishads",
    summary: "The core philosophical Upanishads most commonly studied and most influential.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "shruti",
    depth: 2,
    x: 9.5,
    y: 28,
  },

  {
    id: "isha-upanishad",
    slug: "isha-upanishad",
    title: "Isha Upanishad",
    summary: "Explores the divine essence pervading all existence and the path of non-attachment.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "principal-upanishads",
    depth: 3,
    x: 8.5,
    y: 24,
    href: "/scriptures/isha-upanishad",
  },

  {
    id: "kena-upanishad",
    slug: "kena-upanishad",
    title: "Kena Upanishad",
    summary: "Questions what power moves the universe and who is the supreme consciousness.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "principal-upanishads",
    depth: 3,
    x: 9,
    y: 24,
  },

  {
    id: "katha-upanishad",
    slug: "katha-upanishad",
    title: "Katha Upanishad",
    summary: "Dialogue with Yama on death, the eternal self, and the path to liberation.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "principal-upanishads",
    depth: 3,
    x: 9.5,
    y: 24,
    href: "/scriptures/katha-upanishad",
  },

  {
    id: "mundaka-upanishad",
    slug: "mundaka-upanishad",
    title: "Mundaka Upanishad",
    summary: "Teaches the two forms of knowledge and the path to ultimate reality.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "principal-upanishads",
    depth: 3,
    x: 10,
    y: 24,
  },

  {
    id: "mandukya-upanishad",
    slug: "mandukya-upanishad",
    title: "Mandukya Upanishad",
    summary: "Explores the sacred syllable Om and the states of consciousness.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "principal-upanishads",
    depth: 3,
    x: 10.5,
    y: 24,
  },

  {
    id: "aitareya-upanishad",
    slug: "aitareya-upanishad",
    title: "Aitareya Upanishad",
    summary: "Teaches that Brahman is the ultimate source and ground of all existence.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "principal-upanishads",
    depth: 3,
    x: 11,
    y: 24,
  },

  {
    id: "taittiriya-upanishad",
    slug: "taittiriya-upanishad",
    title: "Taittiriya Upanishad",
    summary: "Explores the essence of Brahman and the nature of Bliss (Ananda).",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "principal-upanishads",
    depth: 3,
    x: 11.5,
    y: 24,
  },

  {
    id: "chandogya-upanishad",
    slug: "chandogya-upanishad",
    title: "Chandogya Upanishad",
    summary: "Contains the famous teaching 'Tat Tvam Asi' (That Thou Art).",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "principal-upanishads",
    depth: 3,
    x: 12,
    y: 24,
    href: "/scriptures/chandogya-upanishad",
  },

  {
    id: "brihadaranyaka-upanishad",
    slug: "brihadaranyaka-upanishad",
    title: "Brihadaranyaka Upanishad",
    summary: "The longest and most comprehensive Upanishad, deep inquiry into Brahman and Atman.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "principal-upanishads",
    depth: 3,
    x: 12.5,
    y: 24,
    href: "/scriptures/brihadaranyaka-upanishad",
  },

  {
    id: "shvetashvatara-upanishad",
    slug: "shvetashvatara-upanishad",
    title: "Shvetashvatara Upanishad",
    summary: "Explores Yoga philosophy and devotion to the Supreme Lord.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "principal-upanishads",
    depth: 3,
    x: 13,
    y: 24,
  },

  // Minor Upanishads
  {
    id: "minor-upanishads",
    slug: "minor-upanishads",
    title: "Minor Upanishads",
    subtitle: "108+ Additional Upanishads",
    summary: "Numerous other Upanishads of varying lengths and approaches, exploring specialized topics.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "shruti",
    depth: 2,
    x: 14,
    y: 28,
  },

  {
    id: "yoga-upanishads",
    slug: "yoga-upanishads",
    title: "Yoga Upanishads",
    summary: "Upanishads focused on Yoga practices and meditation techniques.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "minor-upanishads",
    depth: 3,
    x: 13.5,
    y: 24,
  },

  {
    id: "kali-upanishad",
    slug: "kali-upanishad",
    title: "Kali Upanishad",
    summary: "Teachings on Kundalini and yogic practices.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "yoga-upanishads",
    depth: 4,
    x: 13.2,
    y: 20,
  },

  {
    id: "shakti-upanishads",
    slug: "shakti-upanishads",
    title: "Shakti Upanishads",
    summary: "Upanishads exploring the feminine divine power.",
    nodeType: "SCRIPTURE",
    zone: "SHRUTI",
    parentId: "minor-upanishads",
    depth: 3,
    x: 14.5,
    y: 24,
  },

  // ============================================================
  // SMRITI - REMEMBERED KNOWLEDGE
  // ============================================================

  {
    id: "smriti",
    slug: "smriti",
    title: "Smriti",
    subtitle: "Remembered Knowledge",
    summary: "The scriptures composed and remembered, including epics, shastras, and dharma texts.",
    nodeType: "TRADITION",
    zone: "SMRITI",
    parentId: "sanatana-dharma-root",
    depth: 1,
    x: 25,
    y: 30,
    tags: ["composed", "dharma"],
  },

  // The Great Epics
  {
    id: "mahabharata",
    slug: "mahabharata",
    title: "Mahabharata",
    subtitle: "The Great War",
    summary: "The world's longest epic poem, containing the Bhagavad Gita and teachings on dharma, duty, and liberation.",
    nodeType: "BOOK",
    zone: "SMRITI",
    parentId: "smriti",
    depth: 2,
    x: 23,
    y: 28,
    href: "/books/mahabharata",
  },

  {
    id: "bhagavad-gita",
    slug: "bhagavad-gita",
    title: "Bhagavad Gita",
    subtitle: "Song of the Lord",
    summary: "The dialogue between Krishna and Arjuna on dharma, action, devotion, and knowledge. Central text of Hindu philosophy.",
    nodeType: "BOOK",
    zone: "SMRITI",
    parentId: "mahabharata",
    depth: 3,
    x: 22,
    y: 24,
    tags: ["core", "widely-studied"],
    href: "/books/bhagavad-gita",
  },

  {
    id: "bhishma-parva",
    slug: "bhishma-parva",
    title: "Bhishma Parva",
    summary: "Book of Bhishma, containing teachings and the Gita.",
    nodeType: "SCRIPTURE",
    zone: "SMRITI",
    parentId: "mahabharata",
    depth: 3,
    x: 24,
    y: 24,
  },

  {
    id: "ramayana",
    slug: "ramayana",
    title: "Ramayana",
    subtitle: "The Way of Rama",
    summary: "Epic narrative of Rama's life exemplifying dharma, duty, and virtue. Beloved devotional scripture.",
    nodeType: "BOOK",
    zone: "SMRITI",
    parentId: "smriti",
    depth: 2,
    x: 25,
    y: 28,
    href: "/books/ramayana",
  },

  {
    id: "yoga-vasistha",
    slug: "yoga-vasistha",
    title: "Yoga Vasistha",
    summary: "Stories and teachings within the Ramayana framework on yoga and liberation.",
    nodeType: "SCRIPTURE",
    zone: "SMRITI",
    parentId: "ramayana",
    depth: 3,
    x: 25,
    y: 24,
  },

  // Dharma Shastras (Ethics and Law)
  {
    id: "dharma-shastras",
    slug: "dharma-shastras",
    title: "Dharma Shastras",
    subtitle: "Codes of Conduct",
    summary: "Texts defining righteous living, duties, laws, and social order.",
    nodeType: "SCRIPTURE",
    zone: "SMRITI",
    parentId: "smriti",
    depth: 2,
    x: 27,
    y: 28,
  },

  {
    id: "manu-smriti",
    slug: "manu-smriti",
    title: "Manu Smriti",
    summary: "The Laws of Manu, foundational code of conduct, duties, and social organization.",
    nodeType: "SCRIPTURE",
    zone: "SMRITI",
    parentId: "dharma-shastras",
    depth: 3,
    x: 26.5,
    y: 24,
    href: "/scriptures/manu-smriti",
  },

  {
    id: "yajnavalkya-smriti",
    slug: "yajnavalkya-smriti",
    title: "Yajnavalkya Smriti",
    summary: "Comprehensive dharma code covering conduct, law, and spiritual practices.",
    nodeType: "SCRIPTURE",
    zone: "SMRITI",
    parentId: "dharma-shastras",
    depth: 3,
    x: 27,
    y: 24,
  },

  {
    id: "narada-smriti",
    slug: "narada-smriti",
    title: "Narada Smriti",
    summary: "Text on judicial procedure and dharma by the sage Narada.",
    nodeType: "SCRIPTURE",
    zone: "SMRITI",
    parentId: "dharma-shastras",
    depth: 3,
    x: 27.5,
    y: 24,
  },

  // ============================================================
  // PURANAS
  // ============================================================

  {
    id: "puranas",
    slug: "puranas",
    title: "Puranas",
    subtitle: "Stories of Creation and Divinity",
    summary: "Narratives of creation, gods, heroes, and spiritual teachings. Accessible devotional literature.",
    nodeType: "SCRIPTURE",
    zone: "PURANAS",
    parentId: "sanatana-dharma-root",
    depth: 1,
    x: 45,
    y: 30,
    tags: ["devotional"],
  },

  {
    id: "bhagavata-purana",
    slug: "bhagavata-purana",
    title: "Bhagavata Purana",
    subtitle: "Stories of Lord Krishna",
    summary: "Most beloved Purana, containing stories of Krishna's life and philosophy of devotion.",
    nodeType: "SCRIPTURE",
    zone: "PURANAS",
    parentId: "puranas",
    depth: 2,
    x: 43,
    y: 26,
    tags: ["bhakti-central"],
    href: "/scriptures/bhagavata-purana",
  },

  {
    id: "shiva-purana",
    slug: "shiva-purana",
    title: "Shiva Purana",
    summary: "Teachings and stories related to Shiva, the supreme lord of transformation and meditation.",
    nodeType: "SCRIPTURE",
    zone: "PURANAS",
    parentId: "puranas",
    depth: 2,
    x: 44.5,
    y: 26,
    href: "/scriptures/shiva-purana",
  },

  {
    id: "vishnu-purana",
    slug: "vishnu-purana",
    title: "Vishnu Purana",
    summary: "Stories of Vishnu and his avatars, emphasizing cosmic order and preservation.",
    nodeType: "SCRIPTURE",
    zone: "PURANAS",
    parentId: "puranas",
    depth: 2,
    x: 45.5,
    y: 26,
    href: "/scriptures/vishnu-purana",
  },

  {
    id: "devi-bhagavatam",
    slug: "devi-bhagavatam",
    title: "Devi Bhagavatam",
    summary: "Purana centered on the goddess, the supreme feminine divine power.",
    nodeType: "SCRIPTURE",
    zone: "PURANAS",
    parentId: "puranas",
    depth: 2,
    x: 46.5,
    y: 26,
  },

  {
    id: "markandeya-purana",
    slug: "markandeya-purana",
    title: "Markandeya Purana",
    summary: "Contains the Devi Mahatmya and teachings on the goddess.",
    nodeType: "SCRIPTURE",
    zone: "PURANAS",
    parentId: "puranas",
    depth: 2,
    x: 47,
    y: 26,
  },

  {
    id: "brahma-purana",
    slug: "brahma-purana",
    title: "Brahma Purana",
    summary: "Teachings by Brahma on creation, rituals, and sacred sites.",
    nodeType: "SCRIPTURE",
    zone: "PURANAS",
    parentId: "puranas",
    depth: 2,
    x: 47.5,
    y: 26,
  },

  {
    id: "padma-purana",
    slug: "padma-purana",
    title: "Padma Purana",
    summary: "Large compilation of mythology, cosmology, and spiritual teachings.",
    nodeType: "SCRIPTURE",
    zone: "PURANAS",
    parentId: "puranas",
    depth: 2,
    x: 48,
    y: 26,
  },

  // ============================================================
  // DARSHANAS - SIX PHILOSOPHICAL SCHOOLS
  // ============================================================

  {
    id: "darshanas",
    slug: "darshanas",
    title: "Darshanas",
    subtitle: "Six Classical Philosophical Schools",
    summary: "Six systematic schools of Indian philosophy, each offering a complete way of understanding reality.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "sanatana-dharma-root",
    depth: 1,
    x: 65,
    y: 30,
    tags: ["systematic"],
  },

  // 1. Vedanta
  {
    id: "vedanta",
    slug: "vedanta",
    title: "Vedanta",
    subtitle: "End of the Vedas",
    summary: "Philosophy based on the Upanishads exploring Brahman, Atman, and liberation through knowledge.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "darshanas",
    depth: 2,
    x: 60,
    y: 26,
    tags: ["most-developed"],
    href: "/philosophies/vedanta",
  },

  {
    id: "advaita-vedanta",
    slug: "advaita-vedanta",
    title: "Advaita Vedanta",
    summary: "Non-dual philosophy teaching absolute non-difference between Atman and Brahman.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "vedanta",
    depth: 3,
    x: 58,
    y: 22,
    tags: ["adi-shankara"],
    href: "/philosophies/advaita-vedanta",
  },

  {
    id: "vishishtadvaita",
    slug: "vishishtadvaita",
    title: "Vishishtadvaita",
    summary: "Qualified non-dualism combining devotion with philosophical understanding.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "vedanta",
    depth: 3,
    x: 59.5,
    y: 22,
    tags: ["ramanuja"],
  },

  {
    id: "dvaita",
    slug: "dvaita",
    title: "Dvaita",
    summary: "Dualistic philosophy maintaining eternal difference between God and souls.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "vedanta",
    depth: 3,
    x: 61,
    y: 22,
    tags: ["madhvacharya"],
  },

  {
    id: "achintya-bhedabheda",
    slug: "achintya-bhedabheda",
    title: "Achintya Bhedabheda",
    summary: "Inconceivable difference and non-difference philosophy of Chaitanya.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "vedanta",
    depth: 3,
    x: 62.5,
    y: 22,
    tags: ["chaitanya"],
  },

  {
    id: "shuddhadvaita",
    slug: "shuddhadvaita",
    title: "Shuddhadvaita",
    summary: "Pure non-dualism of Vallabha emphasizing divine play.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "vedanta",
    depth: 3,
    x: 64,
    y: 22,
    tags: ["vallabha"],
  },

  {
    id: "dvaitadvaita",
    slug: "dvaitadvaita",
    title: "Dvaitadvaita",
    summary: "Non-dual dualism of Nimbarka synthesizing difference and non-difference.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "vedanta",
    depth: 3,
    x: 65.5,
    y: 22,
    tags: ["nimbarka"],
  },

  // 2. Sankhya
  {
    id: "sankhya",
    slug: "sankhya",
    title: "Sankhya",
    subtitle: "Enumeration",
    summary: "Dualistic philosophy analyzing consciousness (Purusha) and nature (Prakriti).",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "darshanas",
    depth: 2,
    x: 62.5,
    y: 26,
    href: "/philosophies/sankhya",
  },

  {
    id: "samkhya-karika",
    slug: "samkhya-karika",
    title: "Samkhya Karika",
    summary: "Key text of Sankhya philosophy by Ishvarakrishna.",
    nodeType: "SCRIPTURE",
    zone: "DARSHANAS",
    parentId: "sankhya",
    depth: 3,
    x: 62,
    y: 22,
  },

  // 3. Yoga
  {
    id: "yoga-darshana",
    slug: "yoga-darshana",
    title: "Yoga",
    subtitle: "Union",
    summary: "Philosophy of meditation and mental discipline based on Patanjali's Yoga Sutras.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "darshanas",
    depth: 2,
    x: 65,
    y: 26,
    href: "/philosophies/yoga",
  },

  {
    id: "yoga-sutras",
    slug: "yoga-sutras",
    title: "Yoga Sutras",
    summary: "Patanjali's systematization of yoga philosophy and practice.",
    nodeType: "SCRIPTURE",
    zone: "DARSHANAS",
    parentId: "yoga-darshana",
    depth: 3,
    x: 64.5,
    y: 22,
    href: "/scriptures/yoga-sutras",
  },

  // 4. Nyaya
  {
    id: "nyaya",
    slug: "nyaya",
    title: "Nyaya",
    subtitle: "Logic",
    summary: "School of logical reasoning and epistemology, systematizing valid knowledge.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "darshanas",
    depth: 2,
    x: 67.5,
    y: 26,
  },

  // 5. Vaisheshika
  {
    id: "vaisheshika",
    slug: "vaisheshika",
    title: "Vaisheshika",
    subtitle: "Atomism",
    summary: "Atomic pluralism explaining the world through combinations of eternal atoms.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "darshanas",
    depth: 2,
    x: 70,
    y: 26,
  },

  // 6. Purva Mimamsa
  {
    id: "mimamsa",
    slug: "mimamsa",
    title: "Purva Mimamsa",
    subtitle: "Vedic Interpretation",
    summary: "School of Vedic interpretation focusing on dharma and ritual action.",
    nodeType: "PHILOSOPHY_SCHOOL",
    zone: "DARSHANAS",
    parentId: "darshanas",
    depth: 2,
    x: 72.5,
    y: 26,
  },

  // ============================================================
  // YOGA SYSTEMS
  // ============================================================

  {
    id: "yoga-systems",
    slug: "yoga-systems",
    title: "Yoga Systems",
    subtitle: "Disciplines of Union",
    summary: "Different approaches and methods of spiritual practice and meditation.",
    nodeType: "PRACTICE",
    zone: "YOGA_SYSTEMS",
    parentId: "sanatana-dharma-root",
    depth: 1,
    x: 85,
    y: 30,
    tags: ["practice"],
  },

  {
    id: "karma-yoga",
    slug: "karma-yoga",
    title: "Karma Yoga",
    subtitle: "Yoga of Action",
    summary: "Path of liberation through selfless action performed with detachment.",
    nodeType: "PRACTICE",
    zone: "YOGA_SYSTEMS",
    parentId: "yoga-systems",
    depth: 2,
    x: 81,
    y: 26,
    href: "/practices/karma-yoga",
  },

  {
    id: "bhakti-yoga",
    slug: "bhakti-yoga",
    title: "Bhakti Yoga",
    subtitle: "Yoga of Devotion",
    summary: "Path of liberation through loving devotion to the divine.",
    nodeType: "PRACTICE",
    zone: "YOGA_SYSTEMS",
    parentId: "yoga-systems",
    depth: 2,
    x: 83.5,
    y: 26,
    href: "/practices/bhakti-yoga",
  },

  {
    id: "jnana-yoga",
    slug: "jnana-yoga",
    title: "Jnana Yoga",
    subtitle: "Yoga of Knowledge",
    summary: "Path of liberation through direct knowledge of ultimate reality.",
    nodeType: "PRACTICE",
    zone: "YOGA_SYSTEMS",
    parentId: "yoga-systems",
    depth: 2,
    x: 86,
    y: 26,
    href: "/practices/jnana-yoga",
  },

  {
    id: "raja-yoga",
    slug: "raja-yoga",
    title: "Raja Yoga",
    subtitle: "Royal Yoga",
    summary: "Path of systematic mental discipline and meditation based on Patanjali.",
    nodeType: "PRACTICE",
    zone: "YOGA_SYSTEMS",
    parentId: "yoga-systems",
    depth: 2,
    x: 88.5,
    y: 26,
    href: "/practices/raja-yoga",
  },

  {
    id: "hatha-yoga",
    slug: "hatha-yoga",
    title: "Hatha Yoga",
    subtitle: "Yoga of Force",
    summary: "Path using physical postures and breath control to prepare the body for meditation.",
    nodeType: "PRACTICE",
    zone: "YOGA_SYSTEMS",
    parentId: "yoga-systems",
    depth: 2,
    x: 91,
    y: 26,
    href: "/practices/hatha-yoga",
  },

  {
    id: "kundalini-yoga",
    slug: "kundalini-yoga",
    title: "Kundalini Yoga",
    subtitle: "Yoga of Serpent Power",
    summary: "Path awakening the dormant spiritual energy and raising consciousness.",
    nodeType: "PRACTICE",
    zone: "YOGA_SYSTEMS",
    parentId: "yoga-systems",
    depth: 2,
    x: 93.5,
    y: 26,
  },

  // ============================================================
  // TANTRA
  // ============================================================

  {
    id: "tantra",
    slug: "tantra",
    title: "Tantra",
    subtitle: "Weaving the Sacred",
    summary: "Diverse esoteric traditions working with energy, mantra, ritual, and the feminine divine.",
    nodeType: "TRADITION",
    zone: "TANTRA",
    parentId: "sanatana-dharma-root",
    depth: 1,
    x: 5,
    y: 65,
    tags: ["esoteric"],
  },

  {
    id: "shaiva-tantra",
    slug: "shaiva-tantra",
    title: "Shaiva Tantra",
    summary: "Tantric traditions centered on Shiva as supreme consciousness.",
    nodeType: "TRADITION",
    zone: "TANTRA",
    parentId: "tantra",
    depth: 2,
    x: 3,
    y: 61,
  },

  {
    id: "shakta-tantra",
    slug: "shakta-tantra",
    title: "Shakta Tantra",
    summary: "Tantric traditions honoring Shakti, the divine feminine power.",
    nodeType: "TRADITION",
    zone: "TANTRA",
    parentId: "tantra",
    depth: 2,
    x: 4.5,
    y: 61,
  },

  {
    id: "kaula",
    slug: "kaula",
    title: "Kaula",
    summary: "Tantric tradition emphasizing direct experience and transformation.",
    nodeType: "TRADITION",
    zone: "TANTRA",
    parentId: "tantra",
    depth: 2,
    x: 6,
    y: 61,
  },

  {
    id: "trika",
    slug: "trika",
    title: "Trika",
    summary: "Non-dual Tantric system of Kashmir Shaivism.",
    nodeType: "TRADITION",
    zone: "TANTRA",
    parentId: "tantra",
    depth: 2,
    x: 7.5,
    y: 61,
  },

  {
    id: "sri-vidya",
    slug: "sri-vidya",
    title: "Sri Vidya",
    summary: "Tantric tradition of worshipping the goddess through sacred geometry.",
    nodeType: "TRADITION",
    zone: "TANTRA",
    parentId: "tantra",
    depth: 2,
    x: 9,
    y: 61,
  },

  // ============================================================
  // BHAKTI TRADITIONS
  // ============================================================

  {
    id: "bhakti-traditions",
    slug: "bhakti-traditions",
    title: "Bhakti Traditions",
    subtitle: "Schools of Devotion",
    summary: "Diverse devotional schools emphasizing loving relationship with the divine.",
    nodeType: "TRADITION",
    zone: "BHAKTI",
    parentId: "sanatana-dharma-root",
    depth: 1,
    x: 25,
    y: 65,
    tags: ["devotional"],
  },

  {
    id: "vaishnavism",
    slug: "vaishnavism",
    title: "Vaishnavism",
    subtitle: "Worship of Vishnu",
    summary: "Devotional tradition centered on Vishnu and his avatars, especially Krishna and Rama.",
    nodeType: "TRADITION",
    zone: "BHAKTI",
    parentId: "bhakti-traditions",
    depth: 2,
    x: 22,
    y: 61,
  },

  {
    id: "gaudiya-vaishnava",
    slug: "gaudiya-vaishnava",
    title: "Gaudiya Vaishnava",
    summary: "Lineage of Chaitanya Mahaprabhu emphasizing Krishna devotion and ecstatic bhakti.",
    nodeType: "TRADITION",
    zone: "BHAKTI",
    parentId: "vaishnavism",
    depth: 3,
    x: 20.5,
    y: 57,
  },

  {
    id: "sri-vaishnava",
    slug: "sri-vaishnava",
    title: "Sri Vaishnava",
    summary: "Ramanuja's lineage combining devotion with philosophical understanding.",
    nodeType: "TRADITION",
    zone: "BHAKTI",
    parentId: "vaishnavism",
    depth: 3,
    x: 22,
    y: 57,
  },

  {
    id: "nimbarka",
    slug: "nimbarka",
    title: "Nimbarka Tradition",
    summary: "Lineage emphasizing Krishna's divine play and the service of divine love.",
    nodeType: "TRADITION",
    zone: "BHAKTI",
    parentId: "vaishnavism",
    depth: 3,
    x: 23.5,
    y: 57,
  },

  {
    id: "vallabha",
    slug: "vallabha",
    title: "Vallabha Tradition",
    summary: "Lineage of Vallabhacharya emphasizing Krishna's divine sweetness.",
    nodeType: "TRADITION",
    zone: "BHAKTI",
    parentId: "vaishnavism",
    depth: 3,
    x: 25,
    y: 57,
  },

  {
    id: "ramanandi",
    slug: "ramanandi",
    title: "Ramanandi",
    summary: "Large Vaishnava order founded by Ramananda emphasizing Rama worship.",
    nodeType: "TRADITION",
    zone: "BHAKTI",
    parentId: "vaishnavism",
    depth: 3,
    x: 26.5,
    y: 57,
  },

  {
    id: "shaivism",
    slug: "shaivism",
    title: "Shaivism",
    subtitle: "Worship of Shiva",
    summary: "Devotional tradition centered on Shiva as supreme consciousness and lord of meditation.",
    nodeType: "TRADITION",
    zone: "BHAKTI",
    parentId: "bhakti-traditions",
    depth: 2,
    x: 27,
    y: 61,
  },

  {
    id: "shaktism",
    slug: "shaktism",
    title: "Shaktism",
    subtitle: "Worship of Shakti",
    summary: "Devotional tradition centered on Shakti, the goddess, as supreme reality.",
    nodeType: "TRADITION",
    zone: "BHAKTI",
    parentId: "bhakti-traditions",
    depth: 2,
    x: 32,
    y: 61,
  },

  {
    id: "smarta-tradition",
    slug: "smarta-tradition",
    title: "Smarta Tradition",
    summary: "Non-sectarian tradition acknowledging multiple forms of the divine.",
    nodeType: "TRADITION",
    zone: "BHAKTI",
    parentId: "bhakti-traditions",
    depth: 2,
    x: 37,
    y: 61,
  },

  // ============================================================
  // CORE CONCEPTS
  // ============================================================

  {
    id: "core-concepts",
    slug: "core-concepts",
    title: "Core Concepts",
    subtitle: "Philosophical Foundations",
    summary: "Fundamental ideas that appear throughout Hindu philosophy and practice.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "sanatana-dharma-root",
    depth: 1,
    x: 45,
    y: 65,
    tags: ["foundational"],
  },

  {
    id: "brahman",
    slug: "brahman",
    title: "Brahman",
    summary: "Ultimate reality, the absolute, non-dual consciousness underlying all existence.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 41,
    y: 61,
    href: "/concepts/brahman",
  },

  {
    id: "atman",
    slug: "atman",
    title: "Atman",
    summary: "The Self, eternal consciousness within each being, non-different from Brahman.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 42.5,
    y: 61,
    href: "/concepts/atman",
  },

  {
    id: "maya",
    slug: "maya",
    title: "Maya",
    summary: "Cosmic illusion or power of appearances that veils ultimate reality.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 44,
    y: 61,
    href: "/concepts/maya",
  },

  {
    id: "karma",
    slug: "karma",
    title: "Karma",
    summary: "Law of action and consequence; actions create impressions that shape destiny.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 45.5,
    y: 61,
    href: "/concepts/karma",
  },

  {
    id: "dharma",
    slug: "dharma",
    title: "Dharma",
    summary: "Righteous duty and order; the ethical foundation of living in harmony with cosmic law.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 47,
    y: 61,
    href: "/concepts/dharma",
  },

  {
    id: "moksha",
    slug: "moksha",
    title: "Moksha",
    summary: "Liberation; the ultimate goal of breaking free from the cycle of rebirth.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 48.5,
    y: 61,
    href: "/concepts/moksha",
  },

  {
    id: "samsara",
    slug: "samsara",
    title: "Samsara",
    summary: "The cycle of birth, death, and rebirth; the wheel of worldly existence.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 50,
    y: 61,
  },

  {
    id: "bhakti",
    slug: "bhakti",
    title: "Bhakti",
    summary: "Devotion; loving relationship with the divine, expressing surrender and attachment.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 51.5,
    y: 61,
  },

  {
    id: "jnana",
    slug: "jnana",
    title: "Jnana",
    summary: "Knowledge; direct insight into the nature of reality and one's true nature.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 53,
    y: 61,
  },

  {
    id: "prakriti",
    slug: "prakriti",
    title: "Prakriti",
    summary: "Nature; the material energy and changing field of experience.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 54.5,
    y: 61,
  },

  {
    id: "purusha",
    slug: "purusha",
    title: "Purusha",
    summary: "Consciousness; the eternal witness and source of awareness.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 56,
    y: 61,
  },

  {
    id: "samadhi",
    slug: "samadhi",
    title: "Samadhi",
    summary: "Meditative absorption; unified consciousness where subject-object duality dissolves.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 57.5,
    y: 61,
  },

  {
    id: "gunas",
    slug: "gunas",
    title: "Gunas",
    summary: "Three qualities of nature: Sattva (purity), Rajas (activity), Tamas (inertia).",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 59,
    y: 61,
  },

  {
    id: "ishvara",
    slug: "ishvara",
    title: "Ishvara",
    summary: "The Supreme Lord; divine consciousness with personality and creative power.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 60.5,
    y: 61,
  },

  {
    id: "shakti",
    slug: "shakti",
    title: "Shakti",
    summary: "Power or energy; the divine feminine force that manifests creation.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 62,
    y: 61,
  },

  {
    id: "consciousness",
    slug: "consciousness",
    title: "Consciousness",
    summary: "The fundamental nature of reality and the subject experiencing all knowledge.",
    nodeType: "CONCEPT",
    zone: "CONCEPTS",
    parentId: "core-concepts",
    depth: 2,
    x: 63.5,
    y: 61,
  },

  // ============================================================
  // PRACTICES
  // ============================================================

  {
    id: "practices",
    slug: "practices",
    title: "Spiritual Practices",
    subtitle: "Methods and Disciplines",
    summary: "Various practices and techniques for spiritual development and liberation.",
    nodeType: "PRACTICE",
    zone: "PRACTICES",
    parentId: "sanatana-dharma-root",
    depth: 1,
    x: 65,
    y: 65,
    tags: ["sadhana"],
  },

  {
    id: "meditation",
    slug: "meditation",
    title: "Meditation",
    summary: "Mental discipline and contemplative practice for calming the mind and gaining insight.",
    nodeType: "PRACTICE",
    zone: "PRACTICES",
    parentId: "practices",
    depth: 2,
    x: 63,
    y: 61,
  },

  {
    id: "asana",
    slug: "asana",
    title: "Asana",
    summary: "Physical postures in yoga practice for health, stability, and preparation for meditation.",
    nodeType: "PRACTICE",
    zone: "PRACTICES",
    parentId: "practices",
    depth: 2,
    x: 64.5,
    y: 61,
  },

  {
    id: "pranayama",
    slug: "pranayama",
    title: "Pranayama",
    summary: "Breath control practices for regulating prana and preparing the mind.",
    nodeType: "PRACTICE",
    zone: "PRACTICES",
    parentId: "practices",
    depth: 2,
    x: 66,
    y: 61,
  },

  {
    id: "mantra",
    slug: "mantra",
    title: "Mantra",
    summary: "Sacred sound formulas for invoking divine energy and focusing the mind.",
    nodeType: "PRACTICE",
    zone: "PRACTICES",
    parentId: "practices",
    depth: 2,
    x: 67.5,
    y: 61,
  },

  {
    id: "yajna",
    slug: "yajna",
    title: "Yajna",
    summary: "Ritual sacrifice and offering for maintaining cosmic order and spiritual growth.",
    nodeType: "PRACTICE",
    zone: "PRACTICES",
    parentId: "practices",
    depth: 2,
    x: 69,
    y: 61,
  },

  {
    id: "puja",
    slug: "puja",
    title: "Puja",
    summary: "Ritual worship and prayer expressing devotion and reverence to the divine.",
    nodeType: "PRACTICE",
    zone: "PRACTICES",
    parentId: "practices",
    depth: 2,
    x: 70.5,
    y: 61,
  },

  {
    id: "tapasya",
    slug: "tapasya",
    title: "Tapasya",
    summary: "Austerity and self-discipline practices for purifying consciousness.",
    nodeType: "PRACTICE",
    zone: "PRACTICES",
    parentId: "practices",
    depth: 2,
    x: 72,
    y: 61,
  },

  // ============================================================
  // SAINTS AND ACHARYAS
  // ============================================================

  {
    id: "acharyas",
    slug: "acharyas",
    title: "Saints & Acharyas",
    subtitle: "Realized Masters",
    summary: "Great teachers and realized souls who have illuminated the path.",
    nodeType: "TRADITION",
    zone: "ACHARYAS",
    parentId: "sanatana-dharma-root",
    depth: 1,
    x: 85,
    y: 65,
    tags: ["teachers"],
  },

  {
    id: "adi-shankara",
    slug: "adi-shankara",
    title: "Adi Shankara",
    summary: "Founder of Advaita Vedanta; unified India with spiritual knowledge.",
    nodeType: "TRADITION",
    zone: "ACHARYAS",
    parentId: "acharyas",
    depth: 2,
    x: 82,
    y: 61,
  },

  {
    id: "ramanuja",
    slug: "ramanuja",
    title: "Ramanuja",
    summary: "Founder of Vishishtadvaita; integrated devotion with philosophical rigor.",
    nodeType: "TRADITION",
    zone: "ACHARYAS",
    parentId: "acharyas",
    depth: 2,
    x: 83.5,
    y: 61,
  },

  {
    id: "madhvacharya",
    slug: "madhvacharya",
    title: "Madhvacharya",
    summary: "Founder of Dvaita philosophy; emphasized devotion to Vishnu.",
    nodeType: "TRADITION",
    zone: "ACHARYAS",
    parentId: "acharyas",
    depth: 2,
    x: 85,
    y: 61,
  },

  {
    id: "chaitanya-mahaprabhu",
    slug: "chaitanya-mahaprabhu",
    title: "Chaitanya Mahaprabhu",
    summary: "Founder of Gaudiya Vaishnavism; popularized ecstatic devotional practice.",
    nodeType: "TRADITION",
    zone: "ACHARYAS",
    parentId: "acharyas",
    depth: 2,
    x: 86.5,
    y: 61,
  },

  {
    id: "ramakrishna-paramahamsa",
    slug: "ramakrishna-paramahamsa",
    title: "Ramakrishna Paramahamsa",
    summary: "19th century saint who realized all paths lead to the same divine reality.",
    nodeType: "TRADITION",
    zone: "ACHARYAS",
    parentId: "acharyas",
    depth: 2,
    x: 88,
    y: 61,
  },

  {
    id: "swami-vivekananda",
    slug: "swami-vivekananda",
    title: "Swami Vivekananda",
    summary: "Modern interpreter of Vedanta; brought Hindu philosophy to the West.",
    nodeType: "TRADITION",
    zone: "ACHARYAS",
    parentId: "acharyas",
    depth: 2,
    x: 89.5,
    y: 61,
  },
];

/**
 * ============================================================
 * COMPREHENSIVE RELATIONSHIPS
 * ============================================================
 */

export const comprehensiveKnowledgeEdges: KnowledgeEdge[] = [
  // Root relationships
  { id: "edge-1", source: "sanatana-dharma-root", target: "shruti", relationshipType: "BELONGS_TO", label: "foundation", summary: "Shruti forms the eternal foundation", weight: 5 },
  { id: "edge-2", source: "sanatana-dharma-root", target: "smriti", relationshipType: "BELONGS_TO", label: "composed", summary: "Smriti transmits remembered wisdom", weight: 5 },
  { id: "edge-3", source: "sanatana-dharma-root", target: "puranas", relationshipType: "BELONGS_TO", label: "narrative", summary: "Puranas tell stories of divine", weight: 4 },
  { id: "edge-4", source: "sanatana-dharma-root", target: "darshanas", relationshipType: "BELONGS_TO", label: "systems", summary: "Darshanas systematize understanding", weight: 4 },
  { id: "edge-5", source: "sanatana-dharma-root", target: "yoga-systems", relationshipType: "BELONGS_TO", label: "practice", summary: "Yoga systems offer practical paths", weight: 4 },
  { id: "edge-6", source: "sanatana-dharma-root", target: "tantra", relationshipType: "BELONGS_TO", label: "esoteric", summary: "Tantra provides esoteric practices", weight: 3 },
  { id: "edge-7", source: "sanatana-dharma-root", target: "bhakti-traditions", relationshipType: "BELONGS_TO", label: "devotional", summary: "Bhakti offers path of love", weight: 4 },
  { id: "edge-8", source: "sanatana-dharma-root", target: "core-concepts", relationshipType: "EXPLAINS", label: "ideas", summary: "Concepts form philosophical foundation", weight: 4 },
  { id: "edge-9", source: "sanatana-dharma-root", target: "practices", relationshipType: "BELONGS_TO", label: "methods", summary: "Practices enable transformation", weight: 4 },

  // Shruti internal relationships
  { id: "edge-10", source: "shruti", target: "vedas", relationshipType: "BELONGS_TO", label: "ancient", summary: "Vedas are oldest shruti texts", weight: 5 },
  { id: "edge-11", source: "shruti", target: "vedanga", relationshipType: "RELATED_TO", label: "auxiliary", summary: "Vedanga helps understand Vedas", weight: 4 },
  { id: "edge-12", source: "shruti", target: "brahmanas", relationshipType: "BELONGS_TO", label: "commentary", summary: "Brahmanas explain Vedic rituals", weight: 4 },
  { id: "edge-13", source: "shruti", target: "aranyakas", relationshipType: "BELONGS_TO", label: "transition", summary: "Aranyakas bridge ritual to philosophy", weight: 3 },
  { id: "edge-14", source: "shruti", target: "principal-upanishads", relationshipType: "BELONGS_TO", label: "philosophy", summary: "Upanishads are essence of Vedas", weight: 5 },
  { id: "edge-15", source: "shruti", target: "minor-upanishads", relationshipType: "BELONGS_TO", label: "expansion", summary: "Minor Upanishads explore further", weight: 3 },

  // Vedas relationships
  { id: "edge-16", source: "vedas", target: "rigveda", relationshipType: "BELONGS_TO", label: "branch", summary: "Rigveda is collection of hymns", weight: 4 },
  { id: "edge-17", source: "vedas", target: "yajurveda", relationshipType: "BELONGS_TO", label: "branch", summary: "Yajurveda focuses on ritual action", weight: 4 },
  { id: "edge-18", source: "vedas", target: "samaveda", relationshipType: "BELONGS_TO", label: "branch", summary: "Samaveda is chant and music", weight: 4 },
  { id: "edge-19", source: "vedas", target: "atharvaveda", relationshipType: "BELONGS_TO", label: "branch", summary: "Atharvaveda covers practical wisdom", weight: 4 },

  // Vedanga relationships
  { id: "edge-20", source: "vedanga", target: "shiksha", relationshipType: "BELONGS_TO", label: "branch", summary: "Shiksha teaches pronunciation", weight: 3 },
  { id: "edge-21", source: "vedanga", target: "kalpa", relationshipType: "BELONGS_TO", label: "branch", summary: "Kalpa explains rituals", weight: 3 },
  { id: "edge-22", source: "vedanga", target: "vyakarana", relationshipType: "BELONGS_TO", label: "branch", summary: "Vyakarana is Sanskrit grammar", weight: 3 },

  // Upanishads relationships
  { id: "edge-23", source: "principal-upanishads", target: "isha-upanishad", relationshipType: "BELONGS_TO", label: "text", summary: "Isha Upanishad explores renunciation", weight: 3 },
  { id: "edge-24", source: "principal-upanishads", target: "kena-upanishad", relationshipType: "BELONGS_TO", label: "text", summary: "Kena questions ultimate power", weight: 3 },
  { id: "edge-25", source: "principal-upanishads", target: "katha-upanishad", relationshipType: "BELONGS_TO", label: "text", summary: "Katha with Yama on death", weight: 3 },
  { id: "edge-26", source: "principal-upanishads", target: "chandogya-upanishad", relationshipType: "BELONGS_TO", label: "text", summary: "Chandogya teaches Tat Tvam Asi", weight: 3 },
  { id: "edge-27", source: "principal-upanishads", target: "brihadaranyaka-upanishad", relationshipType: "BELONGS_TO", label: "text", summary: "Brihadaranyaka is most comprehensive", weight: 3 },

  // Upanishads to Vedanta
  { id: "edge-28", source: "principal-upanishads", target: "vedanta", relationshipType: "INFLUENCED", label: "basis", summary: "Upanishads are foundation of Vedanta", weight: 5 },

  // Smriti relationships
  { id: "edge-29", source: "smriti", target: "mahabharata", relationshipType: "BELONGS_TO", label: "epic", summary: "Mahabharata is great epic", weight: 5 },
  { id: "edge-30", source: "smriti", target: "ramayana", relationshipType: "BELONGS_TO", label: "epic", summary: "Ramayana is noble epic", weight: 5 },
  { id: "edge-31", source: "smriti", target: "dharma-shastras", relationshipType: "BELONGS_TO", label: "law", summary: "Dharma Shastras define duty", weight: 4 },

  // Mahabharata relationships
  { id: "edge-32", source: "mahabharata", target: "bhagavad-gita", relationshipType: "BELONGS_TO", label: "section", summary: "Gita is within Mahabharata", weight: 5 },
  { id: "edge-33", source: "mahabharata", target: "bhishma-parva", relationshipType: "BELONGS_TO", label: "section", summary: "Bhishma Parva contains teachings", weight: 4 },

  // Gita relationships
  { id: "edge-34", source: "bhagavad-gita", target: "karma-yoga", relationshipType: "EXPLAINS", label: "teaches", summary: "Gita teaches Karma Yoga", weight: 5 },
  { id: "edge-35", source: "bhagavad-gita", target: "bhakti-yoga", relationshipType: "EXPLAINS", label: "teaches", summary: "Gita teaches Bhakti Yoga", weight: 5 },
  { id: "edge-36", source: "bhagavad-gita", target: "jnana-yoga", relationshipType: "EXPLAINS", label: "teaches", summary: "Gita teaches Jnana Yoga", weight: 4 },
  { id: "edge-37", source: "bhagavad-gita", target: "dharma", relationshipType: "EXPLAINS", label: "theme", summary: "Gita explores dharma deeply", weight: 5 },
  { id: "edge-38", source: "bhagavad-gita", target: "karma", relationshipType: "EXPLAINS", label: "theme", summary: "Gita teaches action without attachment", weight: 5 },

  // Darshanas relationships
  { id: "edge-39", source: "darshanas", target: "vedanta", relationshipType: "BELONGS_TO", label: "system", summary: "Vedanta is chief philosophy", weight: 5 },
  { id: "edge-40", source: "darshanas", target: "sankhya", relationshipType: "BELONGS_TO", label: "system", summary: "Sankhya analyzes reality", weight: 4 },
  { id: "edge-41", source: "darshanas", target: "yoga-darshana", relationshipType: "BELONGS_TO", label: "system", summary: "Yoga is meditation system", weight: 4 },
  { id: "edge-42", source: "darshanas", target: "nyaya", relationshipType: "BELONGS_TO", label: "system", summary: "Nyaya is logic system", weight: 3 },
  { id: "edge-43", source: "darshanas", target: "vaisheshika", relationshipType: "BELONGS_TO", label: "system", summary: "Vaisheshika is atomism", weight: 3 },
  { id: "edge-44", source: "darshanas", target: "mimamsa", relationshipType: "BELONGS_TO", label: "system", summary: "Mimamsa interprets Vedas", weight: 3 },

  // Vedanta schools
  { id: "edge-45", source: "vedanta", target: "advaita-vedanta", relationshipType: "BELONGS_TO", label: "school", summary: "Advaita is non-dualism", weight: 4 },
  { id: "edge-46", source: "vedanta", target: "vishishtadvaita", relationshipType: "BELONGS_TO", label: "school", summary: "Vishishtadvaita is qualified non-dualism", weight: 4 },
  { id: "edge-47", source: "vedanta", target: "dvaita", relationshipType: "BELONGS_TO", label: "school", summary: "Dvaita emphasizes difference", weight: 4 },
  { id: "edge-48", source: "vedanta", target: "achintya-bhedabheda", relationshipType: "BELONGS_TO", label: "school", summary: "Achintya unites difference and non-difference", weight: 3 },
  { id: "edge-49", source: "vedanta", target: "shuddhadvaita", relationshipType: "BELONGS_TO", label: "school", summary: "Shuddhadvaita is pure non-dualism", weight: 3 },
  { id: "edge-50", source: "vedanta", target: "dvaitadvaita", relationshipType: "BELONGS_TO", label: "school", summary: "Dvaitadvaita is non-dual dualism", weight: 3 },

  // Yoga Darshana relationships
  { id: "edge-51", source: "yoga-darshana", target: "yoga-sutras", relationshipType: "BELONGS_TO", label: "text", summary: "Yoga Sutras systematize Yoga", weight: 5 },

  // Sankhya relationships
  { id: "edge-52", source: "sankhya", target: "samkhya-karika", relationshipType: "BELONGS_TO", label: "text", summary: "Karika is key Sankhya text", weight: 4 },
  { id: "edge-53", source: "sankhya", target: "yoga-darshana", relationshipType: "RELATED_TO", label: "shared", summary: "Sankhya and Yoga share framework", weight: 4 },
  { id: "edge-54", source: "sankhya", target: "purusha", relationshipType: "EXPLAINS", label: "concept", summary: "Sankhya analyzes Purusha", weight: 5 },
  { id: "edge-55", source: "sankhya", target: "prakriti", relationshipType: "EXPLAINS", label: "concept", summary: "Sankhya explains Prakriti", weight: 5 },

  // Tantra relationships
  { id: "edge-56", source: "tantra", target: "shaiva-tantra", relationshipType: "BELONGS_TO", label: "tradition", summary: "Shaiva Tantra focuses on Shiva", weight: 4 },
  { id: "edge-57", source: "tantra", target: "shakta-tantra", relationshipType: "BELONGS_TO", label: "tradition", summary: "Shakta Tantra focuses on Shakti", weight: 4 },
  { id: "edge-58", source: "tantra", target: "kaula", relationshipType: "BELONGS_TO", label: "tradition", summary: "Kaula is direct path", weight: 3 },
  { id: "edge-59", source: "tantra", target: "trika", relationshipType: "BELONGS_TO", label: "tradition", summary: "Trika is non-dual Tantra", weight: 3 },
  { id: "edge-60", source: "tantra", target: "sri-vidya", relationshipType: "BELONGS_TO", label: "tradition", summary: "Sri Vidya worships divine mother", weight: 4 },

  // Bhakti relationships
  { id: "edge-61", source: "bhakti-traditions", target: "vaishnavism", relationshipType: "BELONGS_TO", label: "tradition", summary: "Vaishnavism worships Vishnu", weight: 5 },
  { id: "edge-62", source: "bhakti-traditions", target: "shaivism", relationshipType: "BELONGS_TO", label: "tradition", summary: "Shaivism worships Shiva", weight: 5 },
  { id: "edge-63", source: "bhakti-traditions", target: "shaktism", relationshipType: "BELONGS_TO", label: "tradition", summary: "Shaktism worships the goddess", weight: 4 },
  { id: "edge-64", source: "bhakti-traditions", target: "smarta-tradition", relationshipType: "BELONGS_TO", label: "tradition", summary: "Smarta is non-sectarian", weight: 3 },

  // Vaishnavism sub-schools
  { id: "edge-65", source: "vaishnavism", target: "gaudiya-vaishnava", relationshipType: "BELONGS_TO", label: "school", summary: "Gaudiya focuses on Krishna", weight: 4 },
  { id: "edge-66", source: "vaishnavism", target: "sri-vaishnava", relationshipType: "BELONGS_TO", label: "school", summary: "Sri Vaishnava follows Ramanuja", weight: 4 },
  { id: "edge-67", source: "vaishnavism", target: "nimbarka", relationshipType: "BELONGS_TO", label: "school", summary: "Nimbarka emphasizes play", weight: 3 },
  { id: "edge-68", source: "vaishnavism", target: "vallabha", relationshipType: "BELONGS_TO", label: "school", summary: "Vallabha celebrates Krishna", weight: 3 },
  { id: "edge-69", source: "vaishnavism", target: "ramanandi", relationshipType: "BELONGS_TO", label: "school", summary: "Ramanandi worships Rama", weight: 4 },

  // Yoga systems relationships
  { id: "edge-70", source: "yoga-systems", target: "karma-yoga", relationshipType: "BELONGS_TO", label: "path", summary: "Karma Yoga is action path", weight: 4 },
  { id: "edge-71", source: "yoga-systems", target: "bhakti-yoga", relationshipType: "BELONGS_TO", label: "path", summary: "Bhakti Yoga is devotion path", weight: 4 },
  { id: "edge-72", source: "yoga-systems", target: "jnana-yoga", relationshipType: "BELONGS_TO", label: "path", summary: "Jnana Yoga is knowledge path", weight: 4 },
  { id: "edge-73", source: "yoga-systems", target: "raja-yoga", relationshipType: "BELONGS_TO", label: "path", summary: "Raja Yoga is meditation path", weight: 4 },
  { id: "edge-74", source: "yoga-systems", target: "hatha-yoga", relationshipType: "BELONGS_TO", label: "path", summary: "Hatha Yoga is physical path", weight: 3 },
  { id: "edge-75", source: "yoga-systems", target: "kundalini-yoga", relationshipType: "BELONGS_TO", label: "path", summary: "Kundalini Yoga awakens energy", weight: 3 },

  // Yoga to specific practices
  { id: "edge-76", source: "raja-yoga", target: "meditation", relationshipType: "RELATED_TO", label: "method", summary: "Raja Yoga uses meditation", weight: 4 },
  { id: "edge-77", source: "hatha-yoga", target: "asana", relationshipType: "RELATED_TO", label: "method", summary: "Hatha Yoga uses postures", weight: 5 },
  { id: "edge-78", source: "hatha-yoga", target: "pranayama", relationshipType: "RELATED_TO", label: "method", summary: "Hatha Yoga uses breathing", weight: 5 },

  // Core concepts relationships
  { id: "edge-79", source: "core-concepts", target: "brahman", relationshipType: "BELONGS_TO", label: "concept", summary: "Brahman is ultimate reality", weight: 5 },
  { id: "edge-80", source: "core-concepts", target: "atman", relationshipType: "BELONGS_TO", label: "concept", summary: "Atman is the self", weight: 5 },
  { id: "edge-81", source: "core-concepts", target: "maya", relationshipType: "BELONGS_TO", label: "concept", summary: "Maya is illusion", weight: 4 },
  { id: "edge-82", source: "core-concepts", target: "karma", relationshipType: "BELONGS_TO", label: "concept", summary: "Karma is action consequence", weight: 5 },
  { id: "edge-83", source: "core-concepts", target: "dharma", relationshipType: "BELONGS_TO", label: "concept", summary: "Dharma is duty", weight: 5 },
  { id: "edge-84", source: "core-concepts", target: "moksha", relationshipType: "BELONGS_TO", label: "concept", summary: "Moksha is liberation", weight: 5 },

  // Concept relationships
  { id: "edge-85", source: "atman", target: "brahman", relationshipType: "RELATED_TO", label: "identity", summary: "Atman and Brahman are same", weight: 5 },
  { id: "edge-86", source: "brahman", target: "consciousness", relationshipType: "RELATED_TO", label: "nature", summary: "Brahman is consciousness", weight: 5 },
  { id: "edge-87", source: "karma", target: "dharma", relationshipType: "RELATED_TO", label: "action", summary: "Karma fulfilled through dharma", weight: 4 },
  { id: "edge-88", source: "samsara", target: "moksha", relationshipType: "RELATED_TO", label: "liberation", summary: "Moksha transcends samsara", weight: 5 },

  // Practices relationships
  { id: "edge-89", source: "practices", target: "meditation", relationshipType: "BELONGS_TO", label: "practice", summary: "Meditation trains mind", weight: 5 },
  { id: "edge-90", source: "practices", target: "asana", relationshipType: "BELONGS_TO", label: "practice", summary: "Asana trains body", weight: 4 },
  { id: "edge-91", source: "practices", target: "pranayama", relationshipType: "BELONGS_TO", label: "practice", summary: "Pranayama controls breath", weight: 4 },
  { id: "edge-92", source: "practices", target: "mantra", relationshipType: "BELONGS_TO", label: "practice", summary: "Mantra uses sound", weight: 4 },
  { id: "edge-93", source: "practices", target: "yajna", relationshipType: "BELONGS_TO", label: "practice", summary: "Yajna is ritual", weight: 3 },

  // Teacher relationships
  { id: "edge-94", source: "acharyas", target: "adi-shankara", relationshipType: "BELONGS_TO", label: "teacher", summary: "Shankara founded Advaita", weight: 4 },
  { id: "edge-95", source: "advaita-vedanta", target: "adi-shankara", relationshipType: "INFLUENCED", label: "founder", summary: "Shankara founded this school", weight: 5 },
  { id: "edge-96", source: "acharyas", target: "ramanuja", relationshipType: "BELONGS_TO", label: "teacher", summary: "Ramanuja founded Sri Vaishnava", weight: 4 },
  { id: "edge-97", source: "sri-vaishnava", target: "ramanuja", relationshipType: "INFLUENCED", label: "founder", summary: "Ramanuja founded this school", weight: 5 },
  { id: "edge-98", source: "acharyas", target: "madhvacharya", relationshipType: "BELONGS_TO", label: "teacher", summary: "Madhva founded Dvaita", weight: 4 },
  { id: "edge-99", source: "dvaita", target: "madhvacharya", relationshipType: "INFLUENCED", label: "founder", summary: "Madhva founded this school", weight: 5 },
];
