import type { ConceptProfile, GuidedExplorationPath, KnowledgeEdge, KnowledgeNode } from "@/types/knowledge";

export const knowledgeNodes: KnowledgeNode[] = [
  {
    id: "wisdom-root",
    slug: "sanatana-dharma",
    title: "Sanatana Dharma",
    subtitle: "The civilization archive",
    summary: "A progressive archive for unfolding scriptures, philosophies, practices, concepts, traditions, and teachers step by step.",
    nodeType: "TRADITION",
    difficulty: "beginner",
    guidance: {
      whyItMatters: "Begin here to see the archive as a living civilization of texts, practices, philosophies, and lineages.",
      levelNote: "Best approached as an orientation map before entering any one school.",
      emerged: "The main branches unfold into scripture, practice, philosophy, concepts, teachers, and traditions.",
      recommendedNextIds: ["bhagavad-gita", "karma-yoga", "bhakti", "upanishads", "vedanta"],
    },
    x: 50,
    y: 50,
    tags: ["overview", "archive-root"],
  },
  {
    id: "shruti",
    slug: "shruti",
    title: "Shruti",
    summary: "The heard revelation: Vedas, Brahmanas, Aranyakas, and Upanishads as the foundational scriptural world.",
    nodeType: "SCRIPTURE",
    parentId: "wisdom-root",
    difficulty: "intermediate",
    guidance: {
      whyItMatters: "Shruti is treated as the revealed foundation for Vedic recitation, ritual, and later philosophical inquiry.",
      levelNote: "Enter through the Vedas for historical foundation or through the Upanishads for philosophical study.",
      recommendedNextIds: ["vedas", "upanishads"],
    },
    x: 18,
    y: 22,
    tags: ["foundation", "scripture"],
  },
  {
    id: "smriti",
    slug: "smriti",
    title: "Smriti",
    summary: "The remembered tradition: epics, dharma literature, Puranas, and teaching texts that interpret and carry dharma.",
    nodeType: "SCRIPTURE",
    parentId: "wisdom-root",
    difficulty: "beginner",
    guidance: {
      whyItMatters: "Smriti makes dharma, devotion, ethics, and philosophical teaching narratively accessible.",
      levelNote: "A gentle entry into the civilization through story, dialogue, law, and sacred memory.",
      recommendedNextIds: ["itihasas", "bhagavad-gita", "puranas"],
    },
    x: 36,
    y: 22,
    tags: ["scripture", "tradition"],
  },
  {
    id: "sampradayas",
    slug: "sampradayas",
    title: "Sampradayas",
    summary: "Living teaching lineages and devotional traditions through which ideas, practices, and commentaries are transmitted.",
    nodeType: "TRADITION",
    parentId: "wisdom-root",
    difficulty: "intermediate",
    guidance: {
      whyItMatters: "Sampradayas show how teachings become lived communities, lineages, worship, and interpretation.",
      levelNote: "Helpful after seeing the major texts and practices.",
      emerged: "Vaishnava, Shaiva, Shakta, Smarta, and Tantric streams branch from this view.",
      recommendedNextIds: ["vaishnavism", "shaivism", "shaktism", "tantra"],
    },
    x: 70,
    y: 28,
    tags: ["lineages", "traditions"],
  },
  {
    id: "yogas",
    slug: "yogas",
    title: "Yogas",
    summary: "Disciplined paths of practice: action, knowledge, devotion, meditation, and integral training of attention.",
    nodeType: "PRACTICE",
    parentId: "wisdom-root",
    difficulty: "beginner",
    guidance: {
      whyItMatters: "The yogas organize learning as lived discipline, not only as doctrine.",
      levelNote: "Beginners can start with Karma Yoga and Bhakti Yoga before technical yoga systems.",
      recommendedNextIds: ["karma-yoga", "bhakti-yoga", "raja-yoga"],
    },
    x: 82,
    y: 50,
    tags: ["paths", "practice"],
  },
  {
    id: "practices",
    slug: "practices",
    title: "Practices",
    summary: "Ritual, meditation, mantra, study, service, ethical discipline, and other embodied ways of learning.",
    nodeType: "PRACTICE",
    parentId: "wisdom-root",
    x: 68,
    y: 70,
    tags: ["practice"],
  },
  {
    id: "acharyas",
    slug: "acharyas",
    title: "Acharyas",
    summary: "Teachers, commentators, and lineage-builders who shaped interpretation and transmitted learning across centuries.",
    nodeType: "COMMENTARY",
    parentId: "wisdom-root",
    x: 38,
    y: 74,
    tags: ["teachers", "lineages"],
  },
  {
    id: "vedas",
    slug: "vedas",
    title: "Vedas",
    summary: "The foundational Sanskrit corpus that nourishes later scripture, ritual, philosophy, and contemplation.",
    nodeType: "SCRIPTURE",
    parentId: "shruti",
    era: "Vedic",
    century: "c. 2nd-1st millennium BCE",
    region: "Northwestern and northern India",
    difficulty: "intermediate",
    guidance: {
      whyItMatters: "The Vedas are the oldest textual foundation of the archive and nourish later ritual, philosophy, and recitation lineages.",
      levelNote: "Historically foundational, but often easier after a first orientation through the Gita.",
      emerged: "Brahmanas, Aranyakas, Upanishads, ritual schools, and later Vedantic interpretation draw from this world.",
      recommendedNextIds: ["rigveda", "upanishads", "brahmanas"],
    },
    x: 22,
    y: 28,
    tags: ["source"],
  },
  {
    id: "brahmanas",
    slug: "brahmanas",
    title: "Brahmanas",
    summary: "Ritual and explanatory prose texts that elaborate Vedic sacrifice, order, and sacred action.",
    nodeType: "SCRIPTURE",
    parentId: "shruti",
    x: 32,
    y: 30,
    tags: ["ritual"],
  },
  {
    id: "aranyakas",
    slug: "aranyakas",
    title: "Aranyakas",
    summary: "Forest texts that move from ritual explanation toward contemplative and symbolic interpretation.",
    nodeType: "SCRIPTURE",
    parentId: "shruti",
    x: 42,
    y: 30,
    tags: ["contemplation"],
  },
  {
    id: "upanishads",
    slug: "upanishads",
    title: "Upanishads",
    summary: "Philosophical teachings concerned with self, reality, liberation, and direct understanding.",
    nodeType: "SCRIPTURE",
    parentId: "shruti",
    era: "Late Vedic",
    century: "c. 8th-3rd century BCE",
    region: "Northern India",
    difficulty: "intermediate",
    guidance: {
      whyItMatters: "The Upanishads give the central vocabulary of self, reality, Brahman, and liberation for Vedanta.",
      levelNote: "Intermediate: profound, compact, and best read slowly with guidance.",
      emerged: "Vedanta schools and later renunciant, contemplative, and devotional interpretation grow from this foundation.",
      prerequisiteIds: ["bhagavad-gita"],
      recommendedNextIds: ["vedanta", "brahma-sutras", "atma", "moksha"],
    },
    x: 50,
    y: 18,
    tags: ["self-knowledge"],
  },
  {
    id: "itihasas",
    slug: "itihasas",
    title: "Itihasas",
    summary: "Epic narratives such as the Mahabharata and Ramayana that teach dharma through story, crisis, and example.",
    nodeType: "SCRIPTURE",
    parentId: "smriti",
    x: 62,
    y: 26,
    tags: ["epic"],
  },
  {
    id: "mahabharata",
    slug: "mahabharata",
    title: "Mahabharata",
    summary: "The great epic of dharma, kingship, conflict, devotion, and philosophical crisis within which the Bhagavad Gita appears.",
    nodeType: "SCRIPTURE",
    parentId: "itihasas",
    x: 64,
    y: 29,
    tags: ["epic", "dharma"],
  },
  {
    id: "ramayana",
    slug: "ramayana",
    title: "Ramayana",
    summary: "The epic of Rama, Sita, dharma, exile, devotion, kingship, and the moral imagination of an ideal life.",
    nodeType: "SCRIPTURE",
    parentId: "itihasas",
    x: 68,
    y: 29,
    tags: ["epic", "rama"],
  },
  {
    id: "puranas",
    slug: "puranas",
    title: "Puranas",
    summary: "Narrative, cosmological, devotional, and theological literature that carries tradition through story.",
    nodeType: "SCRIPTURE",
    parentId: "smriti",
    x: 67,
    y: 31,
    tags: ["narrative"],
  },
  {
    id: "dharma-shastras",
    slug: "dharma-shastras",
    title: "Dharma Shastras",
    summary: "Texts concerned with duty, social order, conduct, and juridical or ethical reasoning in context.",
    nodeType: "SCRIPTURE",
    parentId: "smriti",
    x: 72,
    y: 36,
    tags: ["dharma"],
  },
  {
    id: "sutra-literature",
    slug: "sutra-literature",
    title: "Sutra Literature",
    summary: "Concise aphoristic teaching traditions that organize philosophy, practice, ritual, grammar, and interpretation for disciplined study.",
    nodeType: "SCRIPTURE",
    parentId: "smriti",
    x: 76,
    y: 39,
    tags: ["sutra", "study"],
  },
  {
    id: "bhagavad-gita",
    slug: "bhagavad-gita",
    title: "Bhagavad Gita",
    summary: "A dialogue that integrates dharma, action, devotion, meditation, and self-knowledge.",
    nodeType: "BOOK",
    parentId: "mahabharata",
    era: "Epic/Classical",
    century: "c. 2nd century BCE-2nd century CE",
    region: "Pan-Indian epic tradition",
    difficulty: "beginner",
    guidance: {
      whyItMatters: "The Gita is an ideal doorway because it joins action, devotion, knowledge, meditation, and dharma in one dialogue.",
      levelNote: "Beginner to intermediate: accessible in story, deep in interpretation.",
      emerged: "Karma Yoga, Bhakti Yoga, Vedanta commentary, and modern study paths all draw from it.",
      recommendedNextIds: ["karma-yoga", "bhakti", "upanishads", "vedanta"],
    },
    x: 73,
    y: 35,
    href: "/books/bhagavad-gita",
    tags: ["study path"],
  },
  {
    id: "brahma-sutras",
    slug: "brahma-sutras",
    title: "Brahma Sutras",
    summary: "A terse Vedanta source text that systematizes Upanishadic inquiry and becomes the shared ground for later Vedanta commentaries.",
    nodeType: "BOOK",
    parentId: "sutra-literature",
    era: "Classical",
    century: "c. early centuries CE",
    region: "Pan-Indian scholastic Vedanta",
    difficulty: "advanced",
    guidance: {
      whyItMatters: "The Brahma Sutras become the technical meeting ground where Vedanta schools define their interpretations.",
      levelNote: "Advanced: best approached after the Upanishads and Gita.",
      emerged: "Major commentarial traditions of Advaita, Vishishtadvaita, and Dvaita develop around it.",
      prerequisiteIds: ["upanishads", "bhagavad-gita", "vedanta"],
      recommendedNextIds: ["advaita", "vishishtadvaita", "dvaita"],
    },
    x: 78,
    y: 44,
    tags: ["vedanta", "sutra"],
  },
  {
    id: "narada-bhakti-sutras",
    slug: "narada-bhakti-sutras",
    title: "Narada Bhakti Sutras",
    summary: "A concise devotional sutra text that frames bhakti as intense love of the divine and supports later bhakti teaching lineages.",
    nodeType: "BOOK",
    parentId: "sutra-literature",
    era: "Medieval",
    century: "date uncertain, often placed in the medieval period",
    region: "Vaishnava devotional traditions",
    x: 80,
    y: 47,
    tags: ["bhakti", "sutra"],
  },
  {
    id: "bhagavata-purana",
    slug: "bhagavata-purana",
    title: "Bhagavata Purana",
    summary: "A major Purana that centers Krishna devotion, theology, sacred narrative, and the emotional imagination of bhakti.",
    nodeType: "BOOK",
    parentId: "puranas",
    era: "Early Medieval",
    century: "c. 9th-10th century CE",
    region: "Pan-Indian Vaishnava reception",
    difficulty: "intermediate",
    guidance: {
      whyItMatters: "The Bhagavata Purana gives Krishna bhakti a rich narrative, emotional, and theological world.",
      levelNote: "Intermediate: accessible through story, deep in devotional theology.",
      emerged: "Krishna-centered Vaishnava traditions, poetry, and devotional practice are strongly nourished by it.",
      prerequisiteIds: ["bhakti"],
      recommendedNextIds: ["vaishnavism", "mirabai", "vallabhacharya"],
    },
    x: 70,
    y: 34,
    tags: ["purana", "bhakti", "krishna"],
  },
  {
    id: "manusmriti",
    slug: "manusmriti",
    title: "Manusmriti",
    summary: "An influential Dharma Shastra text used to study ancient debates on conduct, social order, law, and ethical authority.",
    nodeType: "BOOK",
    parentId: "dharma-shastras",
    era: "Classical",
    century: "c. 2nd century BCE-3rd century CE",
    region: "North Indian Brahmanical legal traditions",
    difficulty: "advanced",
    guidance: {
      whyItMatters: "Manusmriti is important for studying the history of dharma, conduct, law, and social order.",
      levelNote: "Advanced: read contextually and historically, not as a simple beginner summary of dharma.",
      prerequisiteIds: ["dharma", "dharma-shastras"],
      recommendedNextIds: ["dharma", "mimamsa", "arthashastra"],
    },
    x: 74,
    y: 40,
    tags: ["dharma", "law"],
  },
  {
    id: "arthashastra",
    slug: "arthashastra",
    title: "Arthashastra",
    summary: "A statecraft and political economy text that preserves classical reflection on power, governance, diplomacy, and public order.",
    nodeType: "BOOK",
    parentId: "smriti",
    era: "Classical",
    century: "compiled c. early centuries CE",
    region: "North Indian courtly and political traditions",
    difficulty: "advanced",
    guidance: {
      whyItMatters: "Arthashastra expands the archive beyond spiritual practice into governance, power, security, and public order.",
      levelNote: "Advanced: useful for historical context rather than devotional entry.",
      prerequisiteIds: ["dharma"],
      recommendedNextIds: ["dharma", "manusmriti"],
    },
    x: 79,
    y: 36,
    tags: ["statecraft", "artha"],
  },
  {
    id: "vivekachudamani",
    slug: "vivekachudamani",
    title: "Vivekachudamani",
    summary: "An Advaita teaching text on discrimination, renunciation, self-inquiry, and liberation, influential in later pedagogical study.",
    nodeType: "BOOK",
    parentId: "vedanta",
    era: "Medieval",
    century: "date and authorship debated",
    region: "Advaita Vedanta teaching traditions",
    difficulty: "advanced",
    guidance: {
      whyItMatters: "Vivekachudamani shows how Advaita teaching became a pedagogical path of discrimination and self-inquiry.",
      levelNote: "Advanced: best after basic Vedanta and Advaita orientation.",
      prerequisiteIds: ["vedanta", "advaita"],
      recommendedNextIds: ["adi-shankara", "atma", "moksha"],
    },
    x: 52,
    y: 86,
    tags: ["advaita", "self-inquiry"],
  },
  {
    id: "yoga",
    slug: "yoga",
    title: "Yoga",
    summary: "Disciplines of attention, embodiment, inner steadiness, and liberation.",
    nodeType: "PRACTICE",
    parentId: "yogas",
    philosophicalThemes: ["consciousness", "liberation", "discipline"],
    comparison: {
      coreBelief: "Yoga treats disciplined practice as a means to still mental fluctuation and discern the seer from the seen.",
      atman: "Uses purusha language: consciousness is distinct from prakriti and mental activity.",
      moksha: "Liberation comes through discriminative insight, disciplined concentration, and freedom from misidentification.",
      bhakti: "Can include devotion in later or theistic readings, though classical Yoga is practice-centered.",
      ritual: "Ethical discipline and meditative practice are central; ritual is not the primary frame.",
      vedas: "Generally compatible with orthodox Vedic culture while drawing strongly on Sankhya categories.",
    },
    x: 72,
    y: 65,
    tags: ["practice"],
  },
  {
    id: "karma-yoga",
    slug: "karma-yoga",
    title: "Karma Yoga",
    summary: "The path of disciplined action, responsibility, offering, and freedom from possessive attachment to results.",
    nodeType: "PRACTICE",
    parentId: "yogas",
    difficulty: "beginner",
    guidance: {
      whyItMatters: "Karma Yoga gives beginners a practical way to understand action, duty, and inner steadiness.",
      levelNote: "A natural first practice after the Bhagavad Gita.",
      prerequisiteIds: ["bhagavad-gita"],
      recommendedNextIds: ["karma", "dharma", "samatva"],
    },
    x: 74,
    y: 58,
    tags: ["action"],
  },
  {
    id: "jnana-yoga",
    slug: "jnana-yoga",
    title: "Jnana Yoga",
    summary: "The path of inquiry, discernment, and liberating knowledge of self and reality.",
    nodeType: "PRACTICE",
    parentId: "yogas",
    x: 78,
    y: 62,
    tags: ["knowledge"],
  },
  {
    id: "bhakti-yoga",
    slug: "bhakti-yoga",
    title: "Bhakti Yoga",
    summary: "The path of devotion, remembrance, surrender, worship, and loving relationship with the sacred.",
    nodeType: "PRACTICE",
    parentId: "yogas",
    difficulty: "beginner",
    guidance: {
      whyItMatters: "Bhakti Yoga opens the devotional dimension of the archive through remembrance, worship, and loving surrender.",
      levelNote: "A gentle path for beginners and a deep path in mature traditions.",
      recommendedNextIds: ["bhakti", "vaishnavism", "bhagavata-purana"],
    },
    x: 82,
    y: 66,
    tags: ["devotion"],
  },
  {
    id: "raja-yoga",
    slug: "raja-yoga",
    title: "Raja Yoga",
    summary: "The royal path of meditation, concentration, ethical discipline, and refinement of mind.",
    nodeType: "PRACTICE",
    parentId: "yogas",
    x: 86,
    y: 70,
    tags: ["meditation"],
  },
  {
    id: "vedanta",
    slug: "vedanta",
    title: "Vedanta",
    summary: "A family of philosophical traditions centered on the Upanishads, Brahman, Atma, and liberation.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "darshanas",
    era: "Classical",
    century: "systematized c. 1st millennium CE",
    region: "Pan-Indian scholastic traditions",
    difficulty: "intermediate",
    guidance: {
      whyItMatters: "Vedanta gathers the Upanishads, Gita, and Brahma Sutras into major schools of liberation-focused philosophy.",
      levelNote: "Intermediate: begin with the source texts before entering school debates.",
      emerged: "Advaita, Vishishtadvaita, Dvaita, and other Vedanta lineages emerge through commentary and debate.",
      prerequisiteIds: ["upanishads", "bhagavad-gita"],
      recommendedNextIds: ["upanishads", "bhagavad-gita", "brahma-sutras", "advaita", "vishishtadvaita", "dvaita"],
    },
    x: 48,
    y: 78,
    tags: ["philosophy"],
  },
  {
    id: "sankhya",
    slug: "sankhya",
    title: "Sankhya",
    summary: "A philosophical analysis of consciousness, nature, qualities, and discriminative insight.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "darshanas",
    difficulty: "advanced",
    philosophicalThemes: ["consciousness", "liberation", "metaphysics"],
    comparison: {
      coreBelief: "Sankhya analyzes reality through the distinction between purusha, consciousness, and prakriti, nature.",
      atman: "Purusha is pure witnessing consciousness, many in number and distinct from nature.",
      moksha: "Liberation comes through discriminating purusha from prakriti.",
      bhakti: "Not central in classical Sankhya; later traditions may integrate devotional frameworks.",
      ritual: "Ritual is not primary; analysis and discriminative knowledge are central.",
      vedas: "Accepted within the broad orthodox landscape, though its system is strongly analytical.",
    },
    guidance: {
      whyItMatters: "Sankhya gives an analytical vocabulary of purusha and prakriti that deeply informs Yoga.",
      levelNote: "Advanced but useful before studying Yoga psychology closely.",
      recommendedNextIds: ["purusha", "prakriti", "yoga-sutras"],
    },
    x: 25,
    y: 70,
    tags: ["philosophy"],
  },
  {
    id: "tantra",
    slug: "tantra",
    title: "Tantra",
    summary: "Diverse traditions that work with mantra, ritual, embodiment, energy, and sacred presence.",
    nodeType: "TRADITION",
    parentId: "sampradayas",
    era: "Classical/Medieval",
    century: "c. 6th-12th century CE",
    region: "Pan-Indian, with strong regional lineages",
    difficulty: "advanced",
    philosophicalThemes: ["ritual", "non-duality", "embodiment"],
    comparison: {
      coreBelief: "Tantric traditions often treat body, mantra, deity, ritual, and awareness as means of transformation.",
      brahman: "Varies by lineage; many traditions frame ultimate reality through Shiva, Shakti, or divine consciousness.",
      atman: "Often interpreted through embodied awareness or participation in divine power, depending on lineage.",
      moksha: "Liberation may be framed as recognition, union, empowerment, or transformed participation in sacred reality.",
      bhakti: "Devotion can be important, especially in deity-centered traditions, but it is integrated with mantra and ritual.",
      ritual: "Ritual is central and often understood as transformative rather than merely symbolic.",
      vedas: "Tantra develops alongside Vedic tradition with its own scriptures, lineages, and ritual authorities.",
    },
    guidance: {
      whyItMatters: "Tantra shows how mantra, ritual, body, energy, deity, and non-dual practice shaped many medieval traditions.",
      levelNote: "Advanced: best studied with historical context and tradition-specific care.",
      recommendedNextIds: ["kashmir-shaivism", "shaktism", "shaivism"],
    },
    x: 16,
    y: 50,
    tags: ["tradition"],
  },
  {
    id: "vaishnavism",
    slug: "vaishnavism",
    title: "Vaishnavism",
    summary: "Traditions centered on Vishnu, Narayana, Krishna, Rama, devotion, theology, and lineage transmission.",
    nodeType: "TRADITION",
    parentId: "sampradayas",
    difficulty: "intermediate",
    guidance: {
      whyItMatters: "Vaishnavism shows bhakti becoming theology, temple practice, poetry, and lineage.",
      levelNote: "Approachable through bhakti, then deepened through Vedanta schools and saints.",
      recommendedNextIds: ["bhakti", "bhagavata-purana", "ramanuja", "alvars", "vallabhacharya"],
    },
    x: 20,
    y: 44,
    tags: ["tradition", "bhakti"],
  },
  {
    id: "shaivism",
    slug: "shaivism",
    title: "Shaivism",
    summary: "Traditions centered on Shiva, including devotional, philosophical, yogic, and tantric streams.",
    nodeType: "TRADITION",
    parentId: "sampradayas",
    x: 24,
    y: 48,
    tags: ["tradition"],
  },
  {
    id: "shaktism",
    slug: "shaktism",
    title: "Shaktism",
    summary: "Traditions centered on Devi, Shakti, sacred power, worship, mantra, and embodied spiritual practice.",
    nodeType: "TRADITION",
    parentId: "sampradayas",
    x: 28,
    y: 52,
    tags: ["tradition"],
  },
  {
    id: "smarta",
    slug: "smarta",
    title: "Smarta",
    summary: "A tradition associated with Vedic learning, household worship, Advaita interpretation, and integrated deity practice.",
    nodeType: "TRADITION",
    parentId: "sampradayas",
    x: 32,
    y: 56,
    tags: ["tradition"],
  },
  {
    id: "kashmir-shaivism",
    slug: "kashmir-shaivism",
    title: "Kashmir Shaivism",
    summary: "A non-dual Shaiva tradition that links consciousness, recognition, aesthetics, ritual, and tantric practice.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "shaivism",
    era: "Medieval",
    century: "c. 9th-11th century CE",
    region: "Kashmir",
    difficulty: "advanced",
    guidance: {
      whyItMatters: "Kashmir Shaivism links non-dual philosophy, recognition, aesthetics, and tantric practice in a sophisticated Shaiva synthesis.",
      levelNote: "Advanced: best after a basic understanding of Tantra and non-dual traditions.",
      prerequisiteIds: ["tantra", "shaivism"],
      recommendedNextIds: ["abhinavagupta", "tantra", "advaita"],
    },
    x: 26,
    y: 50,
    tags: ["shaiva", "tantra", "non-dual"],
  },
  {
    id: "darshanas",
    slug: "darshanas",
    title: "Darshanas",
    summary: "Classical philosophical viewpoints, each offering a disciplined way of seeing reality.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "wisdom-root",
    difficulty: "advanced",
    guidance: {
      whyItMatters: "The darshanas preserve rigorous debate about knowledge, reality, action, liberation, and interpretation.",
      levelNote: "Best after gaining some familiarity with the Gita, Upanishads, and basic concepts.",
      recommendedNextIds: ["vedanta", "sankhya", "nyaya", "mimamsa"],
    },
    x: 86,
    y: 50,
    tags: ["systems"],
  },
  {
    id: "concepts",
    slug: "concepts",
    title: "Concepts",
    summary: "Key ideas that connect scriptures and practices across the learning map.",
    nodeType: "CONCEPT",
    parentId: "wisdom-root",
    x: 50,
    y: 50,
    href: "/concepts",
    tags: ["index"],
  },
  {
    id: "svadhyaya",
    slug: "svadhyaya",
    title: "Svadhyaya",
    summary: "Study, recitation, and reflective self-learning through scripture and disciplined attention.",
    nodeType: "PRACTICE",
    parentId: "practices",
    x: 55,
    y: 58,
    tags: ["study"],
  },
  {
    id: "japa",
    slug: "japa",
    title: "Japa",
    summary: "Repetition of mantra as a practice of remembrance, concentration, and devotional refinement.",
    nodeType: "PRACTICE",
    parentId: "practices",
    x: 60,
    y: 61,
    tags: ["mantra"],
  },
  {
    id: "puja",
    slug: "puja",
    title: "Puja",
    summary: "Ritual worship that expresses reverence, offering, relationship, and sacred presence.",
    nodeType: "PRACTICE",
    parentId: "practices",
    x: 65,
    y: 64,
    tags: ["ritual"],
  },
  {
    id: "seva",
    slug: "seva",
    title: "Seva",
    summary: "Service offered as discipline, devotion, humility, and participation in dharma.",
    nodeType: "PRACTICE",
    parentId: "practices",
    x: 70,
    y: 67,
    tags: ["service"],
  },
  {
    id: "adi-shankara",
    slug: "adi-shankara",
    title: "Adi Shankara",
    summary: "A major Advaita Vedanta acharya associated with commentarial, monastic, and philosophical transmission.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Classical",
    century: "8th century CE",
    region: "South India and pan-Indian monastic networks",
    x: 34,
    y: 84,
    tags: ["advaita"],
  },
  {
    id: "ramanuja",
    slug: "ramanuja",
    title: "Ramanuja",
    summary: "A major Vishishtadvaita acharya who shaped devotional Vedanta, theology, and scriptural interpretation.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Medieval",
    century: "11th-12th century CE",
    region: "Tamil Nadu and Srirangam",
    x: 40,
    y: 86,
    tags: ["vishishtadvaita"],
  },
  {
    id: "madhva",
    slug: "madhva",
    title: "Madhva",
    summary: "A Dvaita Vedanta acharya associated with dualist interpretation and devotional philosophical lineage.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Medieval",
    century: "13th century CE",
    region: "Karnataka",
    x: 46,
    y: 88,
    tags: ["dvaita"],
  },
  {
    id: "nimbarkacharya",
    slug: "nimbarkacharya",
    title: "Nimbarkacharya",
    summary: "A Vaishnava Vedanta acharya associated with Dvaitadvaita, Radha-Krishna devotion, and later Nimbarka lineage teaching.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Medieval",
    century: "date debated, commonly placed in the medieval period",
    region: "North Indian Vaishnava traditions",
    x: 48,
    y: 90,
    tags: ["vaishnava", "vedanta", "bhakti"],
  },
  {
    id: "vallabhacharya",
    slug: "vallabhacharya",
    title: "Vallabhacharya",
    summary: "A Vaishnava Vedanta acharya whose Shuddhadvaita and Pushtimarg tradition shaped Krishna devotion and householder worship.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Medieval",
    century: "15th-16th century CE",
    region: "Western and North India",
    x: 50,
    y: 92,
    tags: ["vaishnava", "pushtimarg", "bhakti"],
  },
  {
    id: "abhinavagupta",
    slug: "abhinavagupta",
    title: "Abhinavagupta",
    summary: "A Kashmir Shaiva polymath whose works shaped non-dual Shaiva philosophy, tantra, aesthetics, and the theory of recognition.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Medieval",
    century: "10th-11th century CE",
    region: "Kashmir",
    x: 30,
    y: 90,
    tags: ["shaiva", "tantra", "aesthetics"],
  },
  {
    id: "alvars",
    slug: "alvars",
    title: "Alvars",
    summary: "Tamil Vaishnava poet-saints whose hymns nourished temple devotion and helped prepare the devotional world of Sri Vaishnavism.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Early Medieval",
    century: "c. 6th-9th century CE",
    region: "Tamil Nadu",
    x: 38,
    y: 92,
    tags: ["vaishnava", "tamil", "bhakti"],
  },
  {
    id: "nayanmars",
    slug: "nayanmars",
    title: "Nayanmars",
    summary: "Tamil Shaiva poet-saints whose devotional hymns strengthened temple Shaivism and the public language of bhakti.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Early Medieval",
    century: "c. 6th-9th century CE",
    region: "Tamil Nadu",
    x: 32,
    y: 92,
    tags: ["shaiva", "tamil", "bhakti"],
  },
  {
    id: "tulsidas",
    slug: "tulsidas",
    title: "Tulsidas",
    summary: "A North Indian bhakti poet whose Rama-centered works made devotional theology, ethics, and narrative accessible in vernacular form.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Medieval",
    century: "16th-17th century CE",
    region: "North India",
    x: 42,
    y: 94,
    tags: ["rama", "bhakti", "poetry"],
  },
  {
    id: "mirabai",
    slug: "mirabai",
    title: "Mirabai",
    summary: "A Krishna bhakti saint-poet remembered for songs of personal devotion, longing, and resistance to worldly constraint.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Medieval",
    century: "16th century CE",
    region: "Rajasthan and North India",
    x: 44,
    y: 96,
    tags: ["krishna", "bhakti", "poetry"],
  },
  {
    id: "tukaram",
    slug: "tukaram",
    title: "Tukaram",
    summary: "A Marathi Varkari saint-poet whose abhangs express devotion to Vithoba, moral urgency, and accessible spiritual teaching.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Early Modern",
    century: "17th century CE",
    region: "Maharashtra",
    x: 46,
    y: 98,
    tags: ["varkari", "bhakti", "poetry"],
  },
  {
    id: "kabir",
    slug: "kabir",
    title: "Kabir",
    summary: "A North Indian saint-poet whose songs challenge empty ritual, stress direct devotion, and cross sectarian boundaries.",
    nodeType: "COMMENTARY",
    parentId: "acharyas",
    era: "Medieval",
    century: "15th century CE",
    region: "North India",
    x: 40,
    y: 98,
    tags: ["nirguna", "bhakti", "poetry"],
  },
  {
    id: "rigveda",
    slug: "rigveda",
    title: "Rigveda",
    summary: "A Veda of hymns, praise, invocation, and poetic insight.",
    nodeType: "SCRIPTURE",
    parentId: "vedas",
    x: 8,
    y: 18,
  },
  {
    id: "rigveda-samhita",
    slug: "rigveda-samhita",
    title: "Samhitas",
    summary: "The hymn collections of the Rigveda, preserving praise, invocation, poetic vision, and sacred speech.",
    nodeType: "SCRIPTURE",
    parentId: "rigveda",
    x: 6,
    y: 14,
  },
  {
    id: "rigveda-themes",
    slug: "rigveda-themes",
    title: "Themes",
    summary: "Invocation, rta, yajna, cosmic order, speech, dawn, fire, and the relationship between human and divine worlds.",
    nodeType: "CONCEPT",
    parentId: "rigveda",
    x: 10,
    y: 20,
  },
  {
    id: "rigveda-practices",
    slug: "rigveda-practices",
    title: "Associated Practices",
    summary: "Recitation, hymn study, sacrificial liturgy, contemplative listening, and preservation through oral discipline.",
    nodeType: "PRACTICE",
    parentId: "rigveda",
    x: 14,
    y: 24,
  },
  {
    id: "rigveda-traditions",
    slug: "rigveda-traditions",
    title: "Connected Traditions",
    summary: "Vedic recitation lineages, ritual schools, later Vedantic reflection, and interpretive traditions.",
    nodeType: "TRADITION",
    parentId: "rigveda",
    x: 18,
    y: 28,
  },
  {
    id: "yajurveda",
    slug: "yajurveda",
    title: "Yajurveda",
    summary: "A Veda associated with sacrificial formulas, ritual order, and sacred action.",
    nodeType: "SCRIPTURE",
    parentId: "vedas",
    x: 28,
    y: 12,
  },
  {
    id: "samaveda",
    slug: "samaveda",
    title: "Samaveda",
    summary: "A Veda of chant and melodic recitation, closely tied to liturgical singing.",
    nodeType: "SCRIPTURE",
    parentId: "vedas",
    x: 11,
    y: 34,
  },
  {
    id: "atharvaveda",
    slug: "atharvaveda",
    title: "Atharvaveda",
    summary: "A Veda with hymns, rites, healing concerns, and reflections on daily life.",
    nodeType: "SCRIPTURE",
    parentId: "vedas",
    x: 33,
    y: 34,
  },
  {
    id: "isha-upanishad",
    slug: "isha-upanishad",
    title: "Isha Upanishad",
    summary: "A concise Upanishad exploring renunciation, action, and seeing the divine in all.",
    nodeType: "SCRIPTURE",
    parentId: "upanishads",
    x: 39,
    y: 7,
  },
  {
    id: "katha-upanishad",
    slug: "katha-upanishad",
    title: "Katha Upanishad",
    summary: "A dialogue with Yama on death, the self, and the path of wisdom.",
    nodeType: "SCRIPTURE",
    parentId: "upanishads",
    x: 58,
    y: 6,
  },
  {
    id: "chandogya-upanishad",
    slug: "chandogya-upanishad",
    title: "Chandogya Upanishad",
    summary: "A major Upanishad containing teachings such as tat tvam asi.",
    nodeType: "SCRIPTURE",
    parentId: "upanishads",
    x: 68,
    y: 17,
  },
  {
    id: "brihadaranyaka-upanishad",
    slug: "brihadaranyaka-upanishad",
    title: "Brihadaranyaka Upanishad",
    summary: "A profound Upanishad with expansive inquiry into self, reality, and liberation.",
    nodeType: "SCRIPTURE",
    parentId: "upanishads",
    x: 33,
    y: 19,
  },
  {
    id: "yoga-sutras",
    slug: "yoga-sutras",
    title: "Yoga Sutras",
    summary: "A concise system of yogic psychology, practice, concentration, and liberation.",
    nodeType: "SCRIPTURE",
    parentId: "yoga",
    difficulty: "intermediate",
    guidance: {
      whyItMatters: "The Yoga Sutras organize yoga as discipline of mind, attention, and liberation.",
      levelNote: "Intermediate: compact and technical, but central for yoga foundations.",
      prerequisiteIds: ["yoga", "sankhya"],
      recommendedNextIds: ["raja-yoga", "purusha", "prakriti"],
    },
    x: 87,
    y: 71,
  },
  {
    id: "hatha-yoga-pradipika",
    slug: "hatha-yoga-pradipika",
    title: "Hatha Yoga Pradipika",
    summary: "A medieval Hatha Yoga manual that gathers bodily, breath, energetic, and meditative disciplines for later yoga practice.",
    nodeType: "BOOK",
    parentId: "yoga",
    era: "Medieval",
    century: "15th century CE",
    region: "North India",
    difficulty: "intermediate",
    guidance: {
      whyItMatters: "Hatha Yoga Pradipika preserves medieval bodily and energetic disciplines that shaped later yoga practice.",
      levelNote: "Intermediate: practical vocabulary benefits from context.",
      prerequisiteIds: ["yoga"],
      recommendedNextIds: ["raja-yoga", "yoga-sutras"],
    },
    x: 90,
    y: 74,
    tags: ["hatha", "yoga", "practice"],
  },
  {
    id: "karma",
    slug: "karma",
    title: "Karma",
    summary: "Action, consequence, and the ethical texture of cause and effect.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    x: 64,
    y: 47,
    href: "/concepts/karma",
  },
  {
    id: "dharma",
    slug: "dharma",
    title: "Dharma",
    summary: "Right action, responsibility, order, and truth in context.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    x: 58,
    y: 36,
    href: "/concepts/dharma",
  },
  {
    id: "atma",
    slug: "atma",
    title: "Atma",
    summary: "The self or witnessing principle explored in Vedanta and the Gita.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    x: 50,
    y: 63,
    href: "/concepts/atma",
  },
  {
    id: "samatva",
    slug: "samatva",
    title: "Samatva",
    summary: "Equanimity: steadiness in success, failure, pleasure, and pain.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    x: 72,
    y: 55,
    href: "/concepts/samatva",
  },
  {
    id: "bhakti",
    slug: "bhakti",
    title: "Bhakti",
    summary: "Devotion, loving orientation, and surrender toward the sacred.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    difficulty: "beginner",
    guidance: {
      whyItMatters: "Bhakti is the key to understanding devotional traditions, saints, poetry, worship, and many Vedanta lineages.",
      levelNote: "Beginner-friendly, but philosophically rich in later traditions.",
      recommendedNextIds: ["bhakti-yoga", "bhagavata-purana", "vaishnavism", "mirabai"],
    },
    x: 80,
    y: 40,
    href: "/concepts/bhakti",
  },
  {
    id: "jnana",
    slug: "jnana",
    title: "Jnana",
    summary: "Knowledge or insight that clarifies the nature of self and reality.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    x: 43,
    y: 64,
    href: "/concepts/jnana",
  },
  {
    id: "moksha",
    slug: "moksha",
    title: "Moksha",
    summary: "Liberation from bondage, ignorance, and misidentification.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    difficulty: "intermediate",
    guidance: {
      whyItMatters: "Moksha is the horizon that unites many paths while allowing different schools to disagree about liberation.",
      levelNote: "Best understood by comparing practice paths and philosophical schools.",
      recommendedNextIds: ["jnana-yoga", "vedanta", "yoga-sutras"],
    },
    x: 36,
    y: 76,
    href: "/concepts/moksha",
  },
  {
    id: "prakriti",
    slug: "prakriti",
    title: "Prakriti",
    summary: "Nature, materiality, and the changing field of experience in Sankhya language.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    x: 20,
    y: 82,
    href: "/concepts/prakriti",
  },
  {
    id: "purusha",
    slug: "purusha",
    title: "Purusha",
    summary: "Consciousness or witnessing principle in Sankhya and Yoga contexts.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    x: 15,
    y: 66,
    href: "/concepts/purusha",
  },
  {
    id: "non-duality",
    slug: "non-duality",
    title: "Non-duality",
    summary: "A philosophical theme concerning whether ultimate reality is one without a final second, interpreted differently across traditions.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    difficulty: "advanced",
    x: 28,
    y: 70,
    tags: ["theme", "metaphysics"],
  },
  {
    id: "ritual",
    slug: "ritual",
    title: "Ritual",
    summary: "A theme of sacred action, injunction, worship, and embodied practice, understood differently in Mimamsa, Tantra, and devotion.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    difficulty: "intermediate",
    x: 24,
    y: 58,
    tags: ["theme", "practice"],
  },
  {
    id: "consciousness",
    slug: "consciousness",
    title: "Consciousness",
    summary: "A theme linking purusha, atma, awareness, witnessing, and debates about self and ultimate reality.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    difficulty: "intermediate",
    x: 18,
    y: 72,
    tags: ["theme", "self"],
  },
  {
    id: "epistemology",
    slug: "epistemology",
    title: "Epistemology",
    summary: "The study of valid knowledge, testimony, perception, inference, and how traditions justify philosophical claims.",
    nodeType: "CONCEPT",
    parentId: "concepts",
    difficulty: "advanced",
    x: 30,
    y: 84,
    tags: ["theme", "knowledge"],
  },
  {
    id: "advaita",
    slug: "advaita-vedanta",
    title: "Advaita Vedanta",
    summary: "A non-dual Vedanta tradition emphasizing the identity of Atma and Brahman.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "vedanta",
    difficulty: "advanced",
    philosophicalThemes: ["non-duality", "consciousness", "liberation", "knowledge"],
    comparison: {
      coreBelief: "Advaita teaches non-duality: ultimately Atman and Brahman are not separate.",
      brahman: "Brahman is nirguna, non-dual, and the ultimate reality beyond limiting attributes.",
      atman: "Atman is identical with Brahman when ignorance is removed.",
      moksha: "Liberation is through self-knowledge that dispels avidya, ignorance.",
      bhakti: "Devotion may prepare and purify the mind, but knowledge is decisive in classical Advaita.",
      ritual: "Ritual has preparatory value, but is not the direct means to final liberation.",
      vedas: "The Upanishads, Gita, and Brahma Sutras are read as teaching non-dual knowledge.",
    },
    guidance: {
      whyItMatters: "Advaita is a major Vedanta school centered on non-dual self-knowledge and liberation.",
      levelNote: "Advanced: first understand Upanishads, Gita, and Vedanta sources.",
      prerequisiteIds: ["upanishads", "vedanta"],
      recommendedNextIds: ["adi-shankara", "vivekachudamani", "dvaita"],
    },
    x: 45,
    y: 92,
  },
  {
    id: "vishishtadvaita",
    slug: "vishishtadvaita",
    title: "Vishishtadvaita",
    summary: "A qualified non-dual Vedanta tradition with devotional and theological emphasis.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "vedanta",
    difficulty: "advanced",
    philosophicalThemes: ["devotion", "qualified non-duality", "liberation", "vedanta"],
    comparison: {
      coreBelief: "Vishishtadvaita teaches qualified non-duality: souls and world are real modes of Brahman.",
      brahman: "Brahman is personal, identified with Narayana, and possesses infinite auspicious qualities.",
      atman: "Atman is real, dependent on Brahman, and distinct while inseparably related.",
      moksha: "Liberation is loving service and communion with the personal divine.",
      bhakti: "Bhakti and surrender are central, supported by scriptural knowledge and discipline.",
      ritual: "Temple worship and devotional practice are meaningful expressions of relationship with the divine.",
      vedas: "Vedanta sources are read as affirming a personal, qualified absolute.",
    },
    guidance: {
      whyItMatters: "Vishishtadvaita shows Vedanta as devotional theology centered on a qualified non-dual relation to the divine.",
      levelNote: "Advanced: compare with Advaita and Dvaita after source texts.",
      prerequisiteIds: ["vedanta", "bhakti"],
      recommendedNextIds: ["ramanuja", "alvars", "vaishnavism"],
    },
    x: 58,
    y: 90,
  },
  {
    id: "dvaita",
    slug: "dvaita",
    title: "Dvaita Vedanta",
    summary: "A dualist Vedanta school emphasizing real distinction between the individual self, the world, and Vishnu.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "vedanta",
    era: "Medieval",
    century: "13th century CE",
    region: "Karnataka",
    difficulty: "advanced",
    philosophicalThemes: ["devotion", "dualism", "liberation", "vedanta"],
    comparison: {
      coreBelief: "Dvaita teaches a real and eternal difference between God, souls, and world.",
      brahman: "Brahman is Vishnu, supreme personal reality, independent and perfect.",
      atman: "Individual selves are real, dependent, and distinct from God.",
      moksha: "Liberation is attained through divine grace, right knowledge, and devotion to Vishnu.",
      bhakti: "Bhakti is central as devotion to the supreme Lord.",
      ritual: "Ritual and worship support devotional life when oriented toward Vishnu.",
      vedas: "Vedanta texts are read as affirming real difference and the supremacy of Vishnu.",
    },
    guidance: {
      whyItMatters: "Dvaita offers a powerful dualist Vedanta alternative to Advaita and shapes devotional theism.",
      levelNote: "Advanced: best studied through comparison with other Vedanta schools.",
      prerequisiteIds: ["vedanta", "brahma-sutras"],
      recommendedNextIds: ["madhva", "advaita", "vishishtadvaita"],
    },
    x: 62,
    y: 94,
    tags: ["dvaita", "vaishnava"],
  },
  {
    id: "dvaitadvaita",
    slug: "dvaitadvaita",
    title: "Dvaitadvaita",
    summary: "A Vaishnava Vedanta school associated with Nimbarkacharya, teaching both difference and non-difference between Brahman, souls, and world.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "vedanta",
    era: "Medieval",
    century: "date debated",
    region: "North Indian Vaishnava traditions",
    difficulty: "advanced",
    philosophicalThemes: ["devotion", "difference and non-difference", "vedanta"],
    comparison: {
      coreBelief: "Dvaitadvaita teaches that souls and world are both different from and dependent upon Brahman.",
      brahman: "Brahman is personal, often centered on Krishna, with souls and world inseparably dependent.",
      atman: "Atman is real and distinct, yet not independent from Brahman.",
      moksha: "Liberation is realized through devotion, knowledge, and divine grace.",
      bhakti: "Bhakti is central, especially in Radha-Krishna devotional lineages.",
      ritual: "Devotional practice and worship support the soul's relation to the divine.",
      vedas: "Vedanta sources are interpreted through simultaneous difference and non-difference.",
    },
    guidance: {
      whyItMatters: "Dvaitadvaita adds an important Vaishnava model of relation: neither simple identity nor absolute separation.",
      levelNote: "Advanced: best studied after the major Vedanta source texts and basic school contrasts.",
      prerequisiteIds: ["vedanta", "bhakti"],
      recommendedNextIds: ["nimbarkacharya", "vaishnavism", "dvaita", "vishishtadvaita"],
    },
    x: 64,
    y: 96,
    tags: ["vaishnava", "bhakti"],
  },
  {
    id: "shuddhadvaita",
    slug: "shuddhadvaita",
    title: "Shuddhadvaita",
    summary: "A pure non-dual Vaishnava Vedanta school associated with Vallabhacharya and Krishna-centered Pushtimarg devotion.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "vedanta",
    era: "Medieval",
    century: "15th-16th century CE",
    region: "Western and North India",
    difficulty: "advanced",
    philosophicalThemes: ["devotion", "non-duality", "grace", "vedanta"],
    comparison: {
      coreBelief: "Shuddhadvaita teaches a pure non-duality in which the world is a real manifestation of Krishna/Brahman.",
      brahman: "Brahman is Krishna, full of bliss and divine qualities.",
      atman: "The soul is real and belongs to Brahman's own reality, without reducing devotion to illusion.",
      moksha: "Liberation is loving participation in divine grace and service.",
      bhakti: "Bhakti is central, especially as grace-filled devotion in Pushtimarg.",
      ritual: "Seva and worship are central expressions of loving participation.",
      vedas: "Vedanta sources are read through Krishna-centered pure non-duality.",
    },
    guidance: {
      whyItMatters: "Shuddhadvaita shows how non-dual language can support a rich devotional and grace-centered theology.",
      levelNote: "Advanced: compare with Advaita and other Vaishnava Vedanta schools.",
      prerequisiteIds: ["vedanta", "bhakti"],
      recommendedNextIds: ["vallabhacharya", "bhagavata-purana", "advaita"],
    },
    x: 66,
    y: 98,
    tags: ["vaishnava", "pushtimarg", "bhakti"],
  },
  {
    id: "achintya-bheda-abheda",
    slug: "achintya-bheda-abheda",
    title: "Achintya Bheda Abheda",
    summary: "A Gaudiya Vaishnava Vedanta teaching of inconceivable difference and non-difference between Krishna, souls, and world.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "vedanta",
    era: "Early Modern",
    century: "16th century CE",
    region: "Bengal and Vrindavan Gaudiya traditions",
    difficulty: "advanced",
    philosophicalThemes: ["devotion", "difference and non-difference", "grace", "vedanta"],
    comparison: {
      coreBelief: "Achintya Bheda Abheda teaches that souls and world are simultaneously one with and different from Krishna in an inconceivable relation.",
      brahman: "Krishna is the supreme personal reality, with Brahman and Paramatman understood in relation to him.",
      atman: "The soul is a real, dependent participant in Krishna's energy, distinct yet inseparably related.",
      moksha: "Liberation is loving devotional relationship with Krishna.",
      bhakti: "Bhakti is the central and highest path.",
      ritual: "Chanting, worship, remembrance, and devotional community are central practices.",
      vedas: "Vedanta sources are interpreted through Gaudiya Vaishnava devotional theology.",
    },
    guidance: {
      whyItMatters: "This school gives a major later Vaishnava account of relation without collapsing difference or separation.",
      levelNote: "Advanced: best after bhakti, Bhagavata Purana, and basic Vedanta orientation.",
      prerequisiteIds: ["bhakti", "bhagavata-purana", "vedanta"],
      recommendedNextIds: ["vaishnavism", "bhagavata-purana", "dvaitadvaita"],
    },
    x: 68,
    y: 100,
    tags: ["gaudiya", "vaishnava", "bhakti"],
  },
  {
    id: "nyaya",
    slug: "nyaya",
    title: "Nyaya",
    summary: "A classical school focused on logic, knowledge, reasoning, and valid means of knowing.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "darshanas",
    difficulty: "advanced",
    philosophicalThemes: ["epistemology", "logic", "liberation"],
    comparison: {
      coreBelief: "Nyaya holds that rigorous reasoning and valid knowledge help remove error and support liberation.",
      atman: "Accepts enduring selves and argues for them through reasoned analysis.",
      moksha: "Liberation is linked to true knowledge and removal of false cognition.",
      bhakti: "Theistic Nyaya gives a place to Ishvara, but devotion is not its main method.",
      ritual: "Ritual belongs to the broader orthodox world, while Nyaya's distinctive contribution is logic and epistemology.",
      vedas: "Accepts Vedic authority while also emphasizing inference, perception, comparison, and testimony.",
    },
    guidance: {
      whyItMatters: "Nyaya trains the philosophical tools of reasoning, debate, and valid knowledge used across Indian thought.",
      levelNote: "Advanced: useful after basic concepts and before deeper school comparisons.",
      recommendedNextIds: ["mimamsa", "vedanta"],
    },
    x: 94,
    y: 38,
  },
  {
    id: "mimamsa",
    slug: "mimamsa",
    title: "Mimamsa",
    summary: "A school centered on Vedic interpretation, ritual action, and dharma.",
    nodeType: "PHILOSOPHY_SCHOOL",
    parentId: "darshanas",
    difficulty: "advanced",
    philosophicalThemes: ["ritual", "dharma", "epistemology", "vedas"],
    comparison: {
      coreBelief: "Mimamsa centers Vedic injunction, ritual action, dharma, and the authority of sacred language.",
      brahman: "Does not make Brahman-realization the central concern in the way Vedanta does.",
      atman: "Accepts self in many accounts, but emphasizes action, duty, and ritual efficacy more than self-knowledge.",
      moksha: "Varies by subtradition; early emphasis falls more on dharma and ritual order than Vedantic liberation.",
      bhakti: "Devotion is not the defining category of classical Mimamsa.",
      ritual: "Ritual is central as Vedic duty and as a disciplined interpretation of action.",
      vedas: "The Vedas are authoritative, eternal, and central to knowing dharma.",
    },
    guidance: {
      whyItMatters: "Mimamsa clarifies Vedic interpretation, ritual action, injunction, and dharma, giving background to Vedanta debates.",
      levelNote: "Advanced: best after seeing Vedic and dharma foundations.",
      prerequisiteIds: ["vedas", "dharma"],
      recommendedNextIds: ["vedanta", "dharma", "manusmriti"],
    },
    x: 96,
    y: 60,
  },
];

export const guidedExplorationPaths: GuidedExplorationPath[] = [
  {
    id: "start-here",
    title: "Start Here",
    summary: "A gentle first route through action, devotion, scripture, and philosophy.",
    difficulty: "beginner",
    nodeIds: ["wisdom-root", "bhagavad-gita", "karma-yoga", "bhakti", "upanishads", "vedanta"],
  },
  {
    id: "intro-sanatan-dharma",
    title: "Introduction to Sanatana Dharma",
    summary: "A broad orientation through the archive's main branches before entering specialized study.",
    difficulty: "beginner",
    nodeIds: ["wisdom-root", "smriti", "bhagavad-gita", "yogas", "concepts", "sampradayas"],
  },
  {
    id: "understanding-vedanta",
    title: "Understanding Vedanta",
    summary: "The source-text arc behind Vedanta and its major schools.",
    difficulty: "intermediate",
    nodeIds: ["upanishads", "bhagavad-gita", "brahma-sutras", "vedanta", "advaita", "vishishtadvaita", "dvaita", "dvaitadvaita", "shuddhadvaita"],
  },
  {
    id: "bhakti-traditions",
    title: "Bhakti Traditions",
    summary: "Devotion as scripture, practice, lineage, poetry, and theology.",
    difficulty: "beginner",
    nodeIds: ["bhakti", "bhakti-yoga", "bhagavata-purana", "vaishnavism", "alvars", "mirabai", "tukaram", "kabir"],
  },
  {
    id: "yoga-foundations",
    title: "Yoga Foundations",
    summary: "A structured route from general yoga to practice paths and classical sources.",
    difficulty: "intermediate",
    nodeIds: ["yogas", "karma-yoga", "bhakti-yoga", "raja-yoga", "yoga", "yoga-sutras", "hatha-yoga-pradipika"],
  },
  {
    id: "paths-of-moksha",
    title: "Paths of Moksha",
    summary: "Liberation as understood through knowledge, devotion, disciplined action, and philosophical schools.",
    difficulty: "intermediate",
    nodeIds: ["moksha", "jnana-yoga", "karma-yoga", "bhakti-yoga", "vedanta", "yoga-sutras", "sankhya"],
  },
];

export const knowledgeEdges: KnowledgeEdge[] = [
  edge("wisdom-root", "shruti", "BELONGS_TO", "revealed foundation", "Shruti forms the revealed foundation of the archive.", true, 5),
  edge("wisdom-root", "smriti", "BELONGS_TO", "remembered tradition", "Smriti carries dharma through remembered teaching, story, and interpretation.", true, 5),
  edge("wisdom-root", "darshanas", "BELONGS_TO", "viewpoints", "Darshanas are disciplined ways of seeing.", true, 5),
  edge("wisdom-root", "sampradayas", "BELONGS_TO", "lineages", "Sampradayas transmit knowledge through living traditions.", true, 4),
  edge("wisdom-root", "yogas", "BELONGS_TO", "paths", "Yogas organize practice into disciplined paths.", true, 4),
  edge("wisdom-root", "practices", "BELONGS_TO", "embodied learning", "Practices turn knowledge into lived discipline.", true, 4),
  edge("wisdom-root", "concepts", "BELONGS_TO", "ideas", "Concepts connect scriptures, philosophies, practices, and lineages.", true, 4),
  edge("wisdom-root", "acharyas", "BELONGS_TO", "teachers", "Acharyas preserve, interpret, and transmit the tradition.", true, 4),
  edge("shruti", "vedas", "BELONGS_TO", "veda corpus", "The Vedas are the central corpus within Shruti.", true, 5),
  edge("shruti", "brahmanas", "BELONGS_TO", "ritual explanation", "Brahmanas elaborate ritual order and sacred action.", true, 4),
  edge("shruti", "aranyakas", "BELONGS_TO", "forest reflection", "Aranyakas move ritual knowledge toward symbolic contemplation.", true, 4),
  edge("shruti", "upanishads", "BELONGS_TO", "inner inquiry", "Upanishads carry contemplative inquiry into self and reality.", true, 5),
  edge("smriti", "itihasas", "BELONGS_TO", "epic memory", "Itihasas teach dharma through remembered narrative.", true, 5),
  edge("smriti", "puranas", "BELONGS_TO", "sacred story", "Puranas carry cosmology, devotion, and theology through narrative.", true, 4),
  edge("smriti", "dharma-shastras", "BELONGS_TO", "conduct", "Dharma Shastras explore duty, order, and conduct.", true, 4),
  edge("smriti", "sutra-literature", "BELONGS_TO", "aphoristic study", "Sutra literature preserves compact teaching structures for disciplined study.", true, 4),
  edge("smriti", "arthashastra", "BELONGS_TO", "statecraft", "Arthashastra preserves classical reflection on governance, diplomacy, and public order.", true, 3),
  edge("itihasas", "mahabharata", "BELONGS_TO", "great epic", "The Mahabharata teaches dharma through crisis, dialogue, and lineage memory.", true, 5),
  edge("itihasas", "ramayana", "BELONGS_TO", "rama narrative", "The Ramayana teaches dharma through exile, kingship, devotion, and relationship.", true, 5),
  edge("mahabharata", "bhagavad-gita", "BELONGS_TO", "dialogue", "The Gita appears within the Mahabharata and integrates several paths.", true, 5),
  edge("puranas", "bhagavata-purana", "BELONGS_TO", "devotional purana", "The Bhagavata Purana is a major devotional Purana centered on Krishna and bhakti.", true, 5),
  edge("dharma-shastras", "manusmriti", "BELONGS_TO", "dharma text", "Manusmriti is an influential Dharma Shastra text for studying conduct and social order.", true, 4),
  edge("sutra-literature", "brahma-sutras", "BELONGS_TO", "vedanta sutra", "The Brahma Sutras organize Vedanta inquiry in aphoristic form.", true, 5),
  edge("sutra-literature", "narada-bhakti-sutras", "BELONGS_TO", "bhakti sutra", "Narada Bhakti Sutras preserve a concise devotional teaching framework.", true, 4),
  edge("sampradayas", "vaishnavism", "BELONGS_TO", "devotional lineage", "Vaishnavism is a major devotional and theological tradition.", true, 4),
  edge("sampradayas", "shaivism", "BELONGS_TO", "shiva traditions", "Shaivism includes devotional, philosophical, yogic, and tantric streams.", true, 4),
  edge("sampradayas", "shaktism", "BELONGS_TO", "devi traditions", "Shaktism centers sacred power, Devi, mantra, and ritual.", true, 4),
  edge("sampradayas", "smarta", "BELONGS_TO", "integrated worship", "Smarta tradition integrates Vedic learning and household worship.", true, 3),
  edge("sampradayas", "tantra", "BELONGS_TO", "embodied sacredness", "Tantra connects practice, ritual, embodiment, and sacred presence.", true, 3),
  edge("shaivism", "kashmir-shaivism", "BELONGS_TO", "non-dual shaiva school", "Kashmir Shaivism is a major non-dual Shaiva philosophical and tantric tradition.", true, 4),
  edge("yogas", "yoga", "BELONGS_TO", "system", "Yoga offers practices for attention and liberation.", true, 4),
  edge("yogas", "karma-yoga", "BELONGS_TO", "action", "Karma Yoga disciplines action and attachment.", true, 4),
  edge("yogas", "jnana-yoga", "BELONGS_TO", "knowledge", "Jnana Yoga disciplines inquiry and discernment.", true, 4),
  edge("yogas", "bhakti-yoga", "BELONGS_TO", "devotion", "Bhakti Yoga disciplines devotion and remembrance.", true, 4),
  edge("yogas", "raja-yoga", "BELONGS_TO", "meditation", "Raja Yoga disciplines mind, concentration, and meditation.", true, 4),
  edge("practices", "svadhyaya", "BELONGS_TO", "study", "Svadhyaya is scripture study and reflective self-learning.", true, 3),
  edge("practices", "japa", "BELONGS_TO", "mantra", "Japa trains remembrance through mantra repetition.", true, 3),
  edge("practices", "puja", "BELONGS_TO", "worship", "Puja expresses reverence through ritual offering.", true, 3),
  edge("practices", "seva", "BELONGS_TO", "service", "Seva makes service a discipline of humility and offering.", true, 3),
  edge("acharyas", "adi-shankara", "BELONGS_TO", "advaita teacher", "Adi Shankara is a major Advaita Vedanta acharya.", true, 4),
  edge("acharyas", "ramanuja", "BELONGS_TO", "vishishtadvaita teacher", "Ramanuja is a major Vishishtadvaita acharya.", true, 4),
  edge("acharyas", "madhva", "BELONGS_TO", "dvaita teacher", "Madhva is a major Dvaita Vedanta acharya.", true, 4),
  edge("acharyas", "nimbarkacharya", "BELONGS_TO", "vaishnava teacher", "Nimbarkacharya is associated with Radha-Krishna devotion and Dvaitadvaita Vedanta.", true, 3),
  edge("acharyas", "vallabhacharya", "BELONGS_TO", "pushtimarg teacher", "Vallabhacharya shaped Shuddhadvaita and Pushtimarg Krishna devotion.", true, 3),
  edge("acharyas", "abhinavagupta", "BELONGS_TO", "shaiva teacher", "Abhinavagupta is central to Kashmir Shaiva philosophy, tantra, and aesthetics.", true, 4),
  edge("acharyas", "alvars", "BELONGS_TO", "tamil vaishnava saints", "The Alvars helped shape Tamil Vaishnava devotional culture.", true, 3),
  edge("acharyas", "nayanmars", "BELONGS_TO", "tamil shaiva saints", "The Nayanmars helped shape Tamil Shaiva devotional culture.", true, 3),
  edge("acharyas", "tulsidas", "BELONGS_TO", "rama bhakti poet", "Tulsidas carried Rama devotion and ethical narrative into vernacular bhakti.", true, 3),
  edge("acharyas", "mirabai", "BELONGS_TO", "krishna bhakti poet", "Mirabai expresses personal Krishna devotion and devotional longing.", true, 3),
  edge("acharyas", "tukaram", "BELONGS_TO", "varkari poet", "Tukaram's abhangs carry Varkari devotion and moral instruction.", true, 3),
  edge("acharyas", "kabir", "BELONGS_TO", "nirguna poet", "Kabir's songs stress direct devotion and critique empty religious formalism.", true, 3),
  edge("vedas", "rigveda", "BELONGS_TO", "branch", "Rigveda is one of the four Vedas.", true, 4),
  edge("vedas", "yajurveda", "BELONGS_TO", "branch", "Yajurveda is one of the four Vedas.", true, 4),
  edge("vedas", "samaveda", "BELONGS_TO", "branch", "Samaveda is one of the four Vedas.", true, 4),
  edge("vedas", "atharvaveda", "BELONGS_TO", "branch", "Atharvaveda is one of the four Vedas.", true, 4),
  edge("rigveda", "rigveda-samhita", "BELONGS_TO", "textual body", "The Samhita preserves the Rigvedic hymn collections.", true, 3),
  edge("rigveda", "rigveda-themes", "EXPLAINS", "themes", "Rigvedic study opens into themes such as rta, yajna, speech, and cosmic order.", true, 3),
  edge("rigveda", "rigveda-practices", "PRACTICAL_PARALLEL", "practice context", "Rigveda is preserved and encountered through recitation, liturgy, and study.", true, 3),
  edge("rigveda", "rigveda-traditions", "CONTEXTUALIZES", "transmission", "Vedic lineages and later traditions contextualize Rigvedic study.", true, 3),
  edge("vedas", "upanishads", "DERIVED_FROM", "later inquiry", "Many Upanishads are associated with Vedic lineages.", false, 4),
  edge("upanishads", "isha-upanishad", "BELONGS_TO", "major text", "Isha is studied as a principal Upanishad.", true, 3),
  edge("upanishads", "katha-upanishad", "BELONGS_TO", "major text", "Katha is studied as a principal Upanishad.", true, 3),
  edge("upanishads", "chandogya-upanishad", "BELONGS_TO", "major text", "Chandogya is one of the major Upanishads.", true, 3),
  edge("upanishads", "brihadaranyaka-upanishad", "BELONGS_TO", "major text", "Brihadaranyaka is one of the major Upanishads.", true, 3),
  edge("upanishads", "vedanta", "INFLUENCED", "basis", "Vedanta takes the Upanishads as a primary textual basis.", false, 5),
  edge("upanishads", "brahma-sutras", "INFLUENCED", "systematic inquiry", "The Brahma Sutras systematize questions that arise from Upanishadic teaching.", false, 5),
  edge("bhagavad-gita", "karma", "EXPLAINS", "action", "The Gita gives a central teaching on karma and Karma Yoga.", true, 5),
  edge("bhagavad-gita", "dharma", "EXPLAINS", "duty", "The Gita's opening crisis is a crisis of dharma.", true, 5),
  edge("bhagavad-gita", "atma", "EXPLAINS", "self", "The Gita teaches the self beyond bodily change.", true, 4),
  edge("bhagavad-gita", "samatva", "EXPLAINS", "equanimity", "The Gita defines yoga as equanimity in 2.48.", true, 5),
  edge("bhagavad-gita", "bhakti", "EXPLAINS", "devotion", "The Gita develops devotion as a path of relationship and surrender.", true, 4),
  edge("bhagavad-gita", "vedanta", "INFLUENCED", "vedantic synthesis", "The Gita became a central text for Vedanta commentaries and devotional synthesis.", false, 5),
  edge("bhagavata-purana", "bhakti", "EXPLAINS", "krishna devotion", "The Bhagavata Purana gives bhakti a rich narrative and theological world.", true, 5),
  edge("bhagavata-purana", "vaishnavism", "INFLUENCED", "devotional theology", "The Bhagavata Purana strongly influenced Krishna-centered Vaishnava traditions.", false, 5),
  edge("narada-bhakti-sutras", "bhakti", "EXPLAINS", "devotional love", "Narada Bhakti Sutras define bhakti through intense love and surrender.", true, 4),
  edge("yoga", "yoga-sutras", "BELONGS_TO", "system", "The Yoga Sutras systematize yogic practice and psychology.", true, 4),
  edge("yoga", "hatha-yoga-pradipika", "BELONGS_TO", "hatha manual", "Hatha Yoga Pradipika gathers medieval bodily and energetic yoga disciplines.", true, 4),
  edge("yoga", "samatva", "RELATED_TO", "steadiness", "Yogic practice trains steadiness and attention.", true, 3),
  edge("yoga-sutras", "purusha", "EXPLAINS", "witness", "The Yoga Sutras share Sankhya-influenced language around purusha.", false, 3),
  edge("hatha-yoga-pradipika", "raja-yoga", "PRACTICAL_PARALLEL", "practice support", "Hatha Yoga is often framed as preparing steadiness for deeper meditative absorption.", true, 3),
  edge("sankhya", "prakriti", "EXPLAINS", "nature", "Sankhya analyzes prakriti as the field of nature.", true, 5),
  edge("sankhya", "purusha", "EXPLAINS", "consciousness", "Sankhya distinguishes purusha from prakriti.", true, 5),
  edge("sankhya", "yoga", "INFLUENCED", "shared language", "Yoga shares important categories with Sankhya.", true, 3),
  edge("vedanta", "atma", "EXPLAINS", "self", "Vedanta deeply examines Atma and Brahman.", true, 5),
  edge("vedanta", "jnana", "EXPLAINS", "knowledge", "Jnana is central to many Vedanta paths.", true, 4),
  edge("vedanta", "moksha", "EXPLAINS", "liberation", "Vedanta orients inquiry toward liberation.", true, 5),
  edge("vedanta", "advaita", "BELONGS_TO", "school", "Advaita is a Vedanta school.", true, 3),
  edge("vedanta", "vishishtadvaita", "BELONGS_TO", "school", "Vishishtadvaita is a Vedanta school.", true, 3),
  edge("vedanta", "dvaita", "BELONGS_TO", "school", "Dvaita is a Vedanta school shaped by Madhva's dualist theology.", true, 3),
  edge("vedanta", "dvaitadvaita", "BELONGS_TO", "school", "Dvaitadvaita is a Vaishnava Vedanta school associated with Nimbarkacharya.", true, 3),
  edge("vedanta", "shuddhadvaita", "BELONGS_TO", "school", "Shuddhadvaita is a Krishna-centered Vaishnava Vedanta school associated with Vallabhacharya.", true, 3),
  edge("vedanta", "achintya-bheda-abheda", "BELONGS_TO", "school", "Achintya Bheda Abheda is a Gaudiya Vaishnava Vedanta teaching of inconceivable difference and non-difference.", true, 3),
  edge("vedanta", "brahma-sutras", "CONTEXTUALIZES", "source text", "Vedanta schools often define themselves through commentaries on the Brahma Sutras.", true, 5),
  edge("vedanta", "vivekachudamani", "CONTEXTUALIZES", "advaita pedagogy", "Vivekachudamani illustrates later Advaita teaching on discrimination and liberation.", true, 3),
  edge("darshanas", "vedanta", "BELONGS_TO", "school", "Vedanta is one of the classical darshana streams.", true, 4),
  edge("darshanas", "sankhya", "BELONGS_TO", "school", "Sankhya is one of the classical darshana streams.", true, 4),
  edge("darshanas", "nyaya", "BELONGS_TO", "school", "Nyaya is one of the classical systems.", true, 3),
  edge("darshanas", "mimamsa", "BELONGS_TO", "school", "Mimamsa is one of the classical systems.", true, 3),
  edge("mimamsa", "vedanta", "PHILOSOPHICALLY_OPPOSED", "ritual and knowledge", "Mimamsa and Vedanta share Vedic authority but differ over ritual action, knowledge, and liberation.", true, 4, "Both honor the Vedas. Mimamsa asks how Vedic injunction reveals dharma through action; Vedanta asks how the Upanishads reveal Brahman and liberation through knowledge."),
  edge("mimamsa", "vedanta", "CONTEXTUALIZES", "vedic interpretation", "Mimamsa methods provide important background for later Vedanta scriptural interpretation.", false, 3, "Vedanta inherits many tools of textual interpretation from Mimamsa even when it redirects the final emphasis from ritual duty toward Brahman-knowledge."),
  edge("advaita", "dvaita", "PHILOSOPHICALLY_OPPOSED", "non-dual and dualist", "Advaita and Dvaita offer sharply different accounts of self, God, world, and liberation.", true, 5, "They agree on the authority of Vedanta sources and the goal of liberation, but Advaita reads ultimate reality as non-dual identity while Dvaita insists on real and enduring distinction."),
  edge("advaita", "vishishtadvaita", "PHILOSOPHICALLY_SIMILAR", "vedanta debate", "Advaita and Vishishtadvaita share Vedanta sources while disagreeing over non-duality and divine qualification.", true, 4, "Both are Vedanta schools reading the same source triad. Advaita emphasizes nirguna Brahman and identity; Vishishtadvaita emphasizes personal Brahman whose body includes souls and world."),
  edge("vishishtadvaita", "dvaita", "PHILOSOPHICALLY_SIMILAR", "devotional vedanta", "Vishishtadvaita and Dvaita both give devotion and a personal supreme reality a central place.", true, 4, "They agree more strongly on bhakti and the reality of God, soul, and world than Advaita does, while differing over how dependent souls and world relate to Brahman."),
  edge("dvaitadvaita", "achintya-bheda-abheda", "PHILOSOPHICALLY_SIMILAR", "difference and non-difference", "Both schools use difference-and-non-difference language to explain the relation of souls and world to the divine.", true, 4, "Dvaitadvaita frames relation as both difference and non-difference; Achintya Bheda Abheda stresses that this simultaneity is ultimately inconceivable and centered on Krishna devotion."),
  edge("shuddhadvaita", "advaita", "PHILOSOPHICALLY_SIMILAR", "non-dual comparison", "Shuddhadvaita and Advaita both use non-dual language, but differ sharply over world, devotion, and divine qualities.", true, 3, "Advaita often treats the empirical world through maya and stresses knowledge; Shuddhadvaita sees the world as a real manifestation of Krishna and gives devotion and grace central force."),
  edge("advaita", "achintya-bheda-abheda", "PHILOSOPHICALLY_OPPOSED", "identity and relation", "Advaita and Achintya Bheda Abheda both address unity, but differ over final identity, relation, and devotional theology.", true, 3, "Advaita emphasizes ultimate identity of Atman and Brahman; Achintya Bheda Abheda preserves inconceivable difference and non-difference in a Krishna-centered devotional framework."),
  edge("kashmir-shaivism", "tantra", "CONTEXTUALIZES", "tantric framework", "Kashmir Shaivism is deeply intertwined with Shaiva tantric practice and textual culture.", true, 5),
  edge("kashmir-shaivism", "advaita", "PHILOSOPHICALLY_SIMILAR", "non-dual comparison", "Kashmir Shaivism and Advaita both use non-dual language, though their metaphysics and practice frameworks differ.", true, 3),
  edge("karma-yoga", "karma", "EXPLAINS", "action as yoga", "Karma Yoga gives a practical frame for action without possessiveness.", true, 4),
  edge("jnana-yoga", "jnana", "EXPLAINS", "liberating knowledge", "Jnana Yoga makes inquiry and discernment into a path.", true, 4),
  edge("bhakti-yoga", "bhakti", "EXPLAINS", "devotion as path", "Bhakti Yoga turns devotion into a disciplined way of remembrance.", true, 4),
  edge("raja-yoga", "samatva", "PRACTICAL_PARALLEL", "trained steadiness", "Meditative discipline supports steadiness of mind.", true, 3),
  edge("adi-shankara", "advaita", "COMMENTARY_ON", "advaita lineage", "Adi Shankara is central to Advaita Vedanta's commentarial memory.", true, 4),
  edge("ramanuja", "vishishtadvaita", "COMMENTARY_ON", "vishishtadvaita lineage", "Ramanuja is central to Vishishtadvaita's theological and commentarial lineage.", true, 4),
  edge("madhva", "dvaita", "COMMENTARY_ON", "dvaita lineage", "Madhva is central to Dvaita Vedanta's dualist devotional interpretation.", true, 4),
  edge("nimbarkacharya", "vaishnavism", "INFLUENCED", "radha krishna lineage", "Nimbarkacharya is remembered in Vaishnava traditions centered on Radha-Krishna devotion.", false, 3),
  edge("nimbarkacharya", "dvaitadvaita", "COMMENTARY_ON", "dvaitadvaita lineage", "Nimbarkacharya is associated with Dvaitadvaita Vedanta and Radha-Krishna devotion.", true, 4),
  edge("vallabhacharya", "vaishnavism", "INFLUENCED", "pushtimarg lineage", "Vallabhacharya shaped Pushtimarg and Krishna-centered devotional practice.", false, 4),
  edge("vallabhacharya", "shuddhadvaita", "COMMENTARY_ON", "shuddhadvaita lineage", "Vallabhacharya is associated with Shuddhadvaita and Pushtimarg devotional theology.", true, 4),
  edge("bhagavata-purana", "achintya-bheda-abheda", "INFLUENCED", "gaudiya source world", "Gaudiya Vaishnava readings of Achintya Bheda Abheda are deeply shaped by Bhagavata Purana devotion.", false, 4),
  edge("alvars", "vishishtadvaita", "INFLUENCED", "tamil devotional foundation", "Alvar devotional hymns helped form the Tamil devotional background of Sri Vaishnavism.", false, 4),
  edge("nayanmars", "shaivism", "INFLUENCED", "shaiva devotion", "Nayanmar hymns helped shape temple-based Shaiva devotional culture.", false, 4),
  edge("abhinavagupta", "kashmir-shaivism", "COMMENTARY_ON", "shaiva synthesis", "Abhinavagupta is a major interpreter of Kashmir Shaiva philosophy, tantra, and aesthetics.", true, 5),
  edge("tulsidas", "ramayana", "CONTEXTUALIZES", "rama devotion", "Tulsidas represents later Rama devotion and vernacular reception of the Ramayana world.", false, 3),
  edge("mirabai", "bhagavata-purana", "CONTEXTUALIZES", "krishna devotion", "Mirabai's Krishna devotion belongs to the devotional world nourished by Bhagavata traditions.", false, 3),
  edge("tukaram", "bhakti", "EXPLAINS", "varkari devotion", "Tukaram's poetry makes bhakti concrete through moral urgency, song, and accessible teaching.", true, 3),
  edge("kabir", "bhakti", "CONTEXTUALIZES", "nirguna devotion", "Kabir contextualizes a nirguna devotional stream that crosses sectarian boundaries.", true, 3),
  edge("bhakti-yoga", "vaishnavism", "PHILOSOPHICALLY_SIMILAR", "devotional orientation", "Vaishnava traditions often develop bhakti into theology, practice, and communal lineage.", true, 4),
  edge("mimamsa", "dharma", "EXPLAINS", "interpretation", "Mimamsa contributes important ways of thinking about dharma.", true, 3),
  edge("manusmriti", "dharma", "EXPLAINS", "social duty", "Manusmriti is studied as a major text in the history of dharma, conduct, and social order.", true, 3),
  edge("arthashastra", "dharma", "CONTEXTUALIZES", "governance context", "Arthashastra contextualizes dharma alongside power, policy, security, and public order.", true, 3),
  edge("karma", "dharma", "RELATED_TO", "action in context", "Karma becomes meaningful when action is understood through dharma.", true, 4),
  edge("karma", "samatva", "RELATED_TO", "inner posture", "Karma Yoga asks for action with equanimity.", true, 4),
  edge("atma", "moksha", "RELATED_TO", "liberation", "Self-knowledge is linked to liberation in Vedanta contexts.", true, 4),
  edge("jnana", "moksha", "RELATED_TO", "liberating insight", "Knowledge is treated as liberating insight in several traditions.", true, 4),
  edge("advaita", "non-duality", "EXPLAINS", "non-dual theme", "Advaita gives one of the archive's clearest formulations of non-duality.", true, 4),
  edge("shuddhadvaita", "non-duality", "EXPLAINS", "pure non-duality", "Shuddhadvaita connects non-duality with Krishna-centered devotion and grace.", true, 3),
  edge("kashmir-shaivism", "non-duality", "EXPLAINS", "shaiva non-duality", "Kashmir Shaivism develops a Shaiva tantric form of non-dual philosophy.", true, 4),
  edge("sankhya", "consciousness", "EXPLAINS", "purusha", "Sankhya frames consciousness through purusha, distinct from prakriti.", true, 4),
  edge("yoga", "consciousness", "PRACTICAL_PARALLEL", "seer and mind", "Yoga turns the distinction between seer and mental activity into disciplined practice.", true, 4),
  edge("nyaya", "epistemology", "EXPLAINS", "valid knowledge", "Nyaya develops tools for reasoning, debate, and valid means of knowledge.", true, 5),
  edge("mimamsa", "epistemology", "EXPLAINS", "scriptural knowledge", "Mimamsa develops theories of Vedic authority, language, and injunction.", true, 4),
  edge("mimamsa", "ritual", "EXPLAINS", "vedic action", "Mimamsa treats ritual action as central to understanding dharma.", true, 5),
  edge("tantra", "ritual", "EXPLAINS", "embodied rite", "Tantra gives ritual an embodied, mantric, and deity-centered role.", true, 4),
  edge("bhakti", "non-duality", "CONTEXTUALIZES", "devotion and metaphysics", "Some bhakti schools use non-dual or difference-and-non-difference language while preserving devotion.", true, 3),
];

export const conceptProfiles: ConceptProfile[] = [
  {
    slug: "karma",
    title: "Karma",
    category: "Action and consequence",
    summary: "Karma means action and the moral-psychological continuity of action, intention, and consequence.",
    explanation:
      "In the Bhagavad Gita study path, karma is best approached first as responsibility for action. Interpretive traditions then explore how intention, attachment, duty, and consequence shape the inner life.",
    definitions: [
      {
        title: "Action as responsibility",
        definition: "Karma first means action: what is done through body, speech, intention, and attention.",
        context: "For beginning Gita study, this keeps the concept concrete before moving into metaphysics.",
        tradition: "Sanatana Dharma",
        sourceLabel: "Bhagavad Gita study context",
      },
      {
        title: "Action with consequence",
        definition: "Karma also names the continuity between action, motive, habit, and consequence.",
        context: "Different schools explain the mechanism differently, so the platform keeps those views separated.",
        tradition: "Darshana traditions",
      },
    ],
    traditionViews: [
      {
        title: "Karma Yoga reading",
        positionSummary: "The Gita turns karma into a discipline of sincere action without possessiveness toward results.",
        nuance: "This reading emphasizes purification of motive and steadiness in action.",
        tradition: "Sanatana Dharma",
        school: "Karma Yoga",
      },
      {
        title: "Mimamsa concern",
        positionSummary: "Mimamsa gives special attention to action, injunction, ritual order, and dharma.",
        nuance: "Its focus should not be flattened into the Gita's devotional or Vedantic interpretations.",
        tradition: "Sanatana Dharma",
        school: "Mimamsa",
        differsFrom: "It approaches action through scriptural duty and ritual interpretation more directly than many contemplative summaries.",
      },
    ],
    misconceptions: [
      {
        title: "Karma is not fatalism",
        correction: "Karma does not mean passively accepting everything as deserved.",
        whyItMatters: "The Gita repeatedly asks for action, discernment, and responsibility.",
      },
      {
        title: "Karma is not only reward and punishment",
        correction: "It includes intention, habit, duty, and the shaping of consciousness.",
        whyItMatters: "A simplistic reward model can make the teaching morally careless.",
      },
    ],
    practices: [
      {
        title: "Before action",
        description: "Name the duty, the intention, and the attachment you are most likely to carry into the action.",
      },
      {
        title: "After action",
        description: "Review the result as instruction rather than as your identity.",
        caution: "This is contemplative practice, not a way to avoid accountability.",
      },
    ],
    historicalEvolution: [
      {
        period: "Vedic and ritual contexts",
        description: "Action is closely linked with ritual order, duty, and consequences preserved through sacred practice.",
      },
      {
        period: "Gita synthesis",
        description: "The Gita interiorizes action by emphasizing intention, attachment, offering, and disciplined participation in the world.",
      },
    ],
    semanticNeighbors: [
      {
        label: "Dharma",
        relationshipType: "RELATED_TO",
        explanation: "Dharma clarifies what kind of action is fitting; karma studies action and consequence.",
        href: "/concepts/dharma",
      },
      {
        label: "Samatva",
        relationshipType: "PRACTICAL_PARALLEL",
        explanation: "Equanimity describes the inner posture that keeps action from being ruled by success and failure.",
        href: "/concepts/samatva",
      },
    ],
    relatedConceptSlugs: ["dharma", "samatva", "moksha"],
    relatedBooks: [
      {
        title: "Bhagavad Gita",
        href: "/books/bhagavad-gita",
        note: "The Gita gives one of the clearest practical teachings on action without attachment.",
      },
    ],
    relatedVerses: [
      {
        label: "Bhagavad Gita 2.47",
        href: "/books/bhagavad-gita/chapters/2/verses/47",
        note: "Responsibility belongs to action, not ownership over every result.",
      },
      {
        label: "Bhagavad Gita 2.48",
        href: "/books/bhagavad-gita/chapters/2/verses/48",
        note: "Act from yoga, remaining even in success and failure.",
      },
    ],
    relatedPhilosophies: [
      {
        title: "Karma Yoga",
        note: "A discipline of sincere action with reduced attachment to outcome.",
      },
      {
        title: "Mimamsa",
        note: "A classical school with deep concern for action, duty, and Vedic interpretation.",
      },
    ],
    parallels: [
      {
        title: "Habit formation",
        note: "Repeated action shapes tendencies. This is a helpful psychological parallel, not a replacement for the traditional idea of karma.",
      },
    ],
    graphFocusNodeId: "karma",
  },
  {
    slug: "dharma",
    title: "Dharma",
    category: "Ethics and order",
    summary: "Dharma refers to rightness, responsibility, sustaining order, and wise conduct in context.",
    explanation:
      "Dharma is not just a rule. It asks what action is true, responsible, and appropriate to a specific person, role, moment, and moral field.",
    relatedConceptSlugs: ["karma", "samatva"],
    relatedBooks: [
      {
        title: "Bhagavad Gita",
        href: "/books/bhagavad-gita",
        note: "The Gita begins as Arjuna faces a crisis of dharma.",
      },
    ],
    relatedVerses: [
      {
        label: "Bhagavad Gita 1.1",
        href: "/books/bhagavad-gita/chapters/1/verses/1",
        note: "The battlefield is introduced as dharmakshetra, a field of dharma.",
      },
    ],
    relatedPhilosophies: [
      {
        title: "Mimamsa",
        note: "Mimamsa offers detailed approaches to duty, action, and scriptural interpretation.",
      },
    ],
    parallels: [
      {
        title: "Role ethics",
        note: "Modern ethics also studies how responsibility changes with role and context. This is only a parallel for learning.",
      },
    ],
    graphFocusNodeId: "dharma",
  },
  {
    slug: "atma",
    title: "Atma",
    category: "Self-knowledge",
    summary: "Atma points toward the self or witnessing principle explored in the Gita and Vedanta.",
    explanation:
      "The Gita introduces self-inquiry by asking learners to distinguish changing bodily experience from the deeper continuity of the knower.",
    relatedConceptSlugs: ["jnana", "moksha", "purusha"],
    relatedBooks: [
      {
        title: "Bhagavad Gita",
        href: "/books/bhagavad-gita",
        note: "Chapter 2 begins the Gita's teaching on self and embodied change.",
      },
    ],
    relatedVerses: [
      {
        label: "Bhagavad Gita 2.13",
        href: "/books/bhagavad-gita/chapters/2/verses/13",
        note: "A central verse on continuity through bodily change.",
      },
    ],
    relatedPhilosophies: [
      {
        title: "Vedanta",
        note: "Vedanta develops self-knowledge through Upanishadic inquiry.",
      },
    ],
    parallels: [
      {
        title: "Continuity of identity",
        note: "Psychology notices identity continuity across life stages. This is a reflective parallel, not proof of metaphysics.",
      },
    ],
    graphFocusNodeId: "atma",
  },
  {
    slug: "samatva",
    title: "Samatva",
    category: "Mind training",
    summary: "Samatva is equanimity: balanced presence across success, failure, pleasure, and pain.",
    explanation:
      "Samatva is not emotional dullness. It is a trained steadiness that lets action become clearer because the mind is less ruled by outcome.",
    relatedConceptSlugs: ["karma", "dharma"],
    relatedBooks: [
      {
        title: "Bhagavad Gita",
        href: "/books/bhagavad-gita",
        note: "The Gita explicitly calls equanimity yoga in 2.48.",
      },
    ],
    relatedVerses: [
      {
        label: "Bhagavad Gita 2.48",
        href: "/books/bhagavad-gita/chapters/2/verses/48",
        note: "Defines yoga as evenness in success and failure.",
      },
      {
        label: "Bhagavad Gita 2.14",
        href: "/books/bhagavad-gita/chapters/2/verses/14",
        note: "Teaches forbearance toward temporary experiences.",
      },
    ],
    relatedPhilosophies: [
      {
        title: "Yoga",
        note: "Yogic practice trains attention, steadiness, and response rather than reactivity.",
      },
    ],
    parallels: [
      {
        title: "Emotion regulation",
        note: "The pause between stimulus and response is a useful modern parallel, not a total explanation of samatva.",
      },
    ],
    graphFocusNodeId: "samatva",
  },
  {
    slug: "bhakti",
    title: "Bhakti",
    category: "Devotion",
    summary: "Bhakti is a loving orientation toward the sacred, often expressed through surrender, remembrance, and service.",
    explanation:
      "Bhakti should not be reduced to emotion alone. In many traditions it becomes a disciplined relationship of trust, love, humility, and offering.",
    relatedConceptSlugs: ["karma", "moksha"],
    relatedBooks: [
      {
        title: "Bhagavad Gita",
        href: "/books/bhagavad-gita",
        note: "The Gita develops devotion as one of its major paths.",
      },
    ],
    relatedVerses: [],
    relatedPhilosophies: [
      {
        title: "Vishishtadvaita",
        note: "A Vedanta school with a strong devotional orientation.",
      },
    ],
    parallels: [
      {
        title: "Attachment and trust",
        note: "Modern psychology can discuss trust and attachment, but bhakti remains a spiritual category in this context.",
      },
    ],
    graphFocusNodeId: "bhakti",
  },
  {
    slug: "jnana",
    title: "Jnana",
    category: "Knowledge",
    summary: "Jnana is liberating insight, not merely information.",
    explanation:
      "Jnana points to a kind of understanding that changes identity, action, and perception. It is central in many Vedanta-oriented readings.",
    relatedConceptSlugs: ["atma", "moksha"],
    relatedBooks: [
      {
        title: "Upanishads",
        href: "/explore",
        note: "The Upanishads are a major source for self-knowledge inquiry.",
      },
    ],
    relatedVerses: [
      {
        label: "Bhagavad Gita 2.13",
        href: "/books/bhagavad-gita/chapters/2/verses/13",
        note: "A beginner doorway into inquiry about the self.",
      },
    ],
    relatedPhilosophies: [
      {
        title: "Vedanta",
        note: "Vedanta places deep emphasis on knowledge of self and reality.",
      },
    ],
    parallels: [
      {
        title: "Insight learning",
        note: "A psychological parallel is the difference between memorized data and insight that reorganizes perception.",
      },
    ],
    graphFocusNodeId: "jnana",
  },
  {
    slug: "moksha",
    title: "Moksha",
    category: "Liberation",
    summary: "Moksha means liberation from bondage, ignorance, and misidentification.",
    explanation:
      "Different traditions explain moksha differently. The graph treats those explanations as connected interpretations rather than one flattened answer.",
    relatedConceptSlugs: ["atma", "jnana", "bhakti"],
    relatedBooks: [
      {
        title: "Bhagavad Gita",
        href: "/books/bhagavad-gita",
        note: "The Gita integrates action, knowledge, devotion, and meditation toward liberation.",
      },
    ],
    relatedVerses: [],
    relatedPhilosophies: [
      {
        title: "Vedanta",
        note: "Vedanta traditions often place moksha at the center of inquiry.",
      },
      {
        title: "Yoga",
        note: "Yoga traditions describe liberation through disciplined practice and insight.",
      },
    ],
    parallels: [
      {
        title: "Freedom from compulsion",
        note: "Psychological freedom from compulsive patterns can be a learning parallel, not a full equivalent.",
      },
    ],
    graphFocusNodeId: "moksha",
  },
  {
    slug: "prakriti",
    title: "Prakriti",
    category: "Nature",
    summary: "Prakriti refers to nature, materiality, and the changing field of experience in Sankhya language.",
    explanation:
      "Sankhya uses prakriti to analyze the changing field of mind, matter, and qualities. It is understood alongside purusha.",
    relatedConceptSlugs: ["purusha"],
    relatedBooks: [
      {
        title: "Explore Sankhya",
        href: "/explore",
        note: "The graph connects prakriti to Sankhya and Yoga language.",
      },
    ],
    relatedVerses: [],
    relatedPhilosophies: [
      {
        title: "Sankhya",
        note: "Sankhya distinguishes prakriti from purusha.",
      },
    ],
    parallels: [
      {
        title: "Field of experience",
        note: "As a study aid, prakriti can be compared to the observable field of changing experience.",
      },
    ],
    graphFocusNodeId: "prakriti",
  },
  {
    slug: "purusha",
    title: "Purusha",
    category: "Consciousness",
    summary: "Purusha points to consciousness or the witnessing principle in Sankhya and Yoga contexts.",
    explanation:
      "Purusha is studied in relationship to prakriti. The learner should keep this as philosophical vocabulary, not as a casual synonym for personality.",
    relatedConceptSlugs: ["prakriti", "atma"],
    relatedBooks: [
      {
        title: "Yoga Sutras",
        href: "/explore",
        note: "Yoga uses related language when discussing seer and seen.",
      },
    ],
    relatedVerses: [],
    relatedPhilosophies: [
      {
        title: "Sankhya",
        note: "Purusha is central to Sankhya's distinction between consciousness and nature.",
      },
      {
        title: "Yoga",
        note: "Yoga inherits and adapts important Sankhya categories.",
      },
    ],
    parallels: [
      {
        title: "Witnessing awareness",
        note: "Meditation language sometimes uses witnessing as a practical pointer; this remains only an aid to understanding.",
      },
    ],
    graphFocusNodeId: "purusha",
  },
];

function edge(
  source: string,
  target: string,
  relationshipType: KnowledgeEdge["relationshipType"],
  label: string,
  summary: string,
  bidirectional: boolean,
  weight: number,
  explanation?: string,
): KnowledgeEdge {
  return {
    id: `${source}-${relationshipType.toLowerCase()}-${target}`,
    source,
    target,
    relationshipType,
    label,
    summary,
    explanation,
    bidirectional,
    weight,
  };
}

export function getKnowledgeNode(id: string) {
  return knowledgeNodes.find((node) => node.id === id);
}

export function getConceptProfile(slug: string) {
  return conceptProfiles.find((concept) => concept.slug === slug);
}

export function getRelatedEdges(nodeId: string) {
  return knowledgeEdges.filter((edge) => edge.source === nodeId || edge.target === nodeId);
}

export function getNeighborNodeIds(nodeId: string) {
  return Array.from(
    new Set(
      getRelatedEdges(nodeId).flatMap((edge) => [edge.source, edge.target]).filter((id) => id !== nodeId),
    ),
  );
}
